import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabase'
import { RESPONSIBILITY_LABELS, type EmployeeProfile, type EmployeeSkill, type ManpowerEmployee, type QualificationStatus, type ResponsibilityLevel } from '../../lib/planManpower'
import NewEmployeeEvaluationPanel from './NewEmployeeEvaluationPanel'

type Props={departments:string[];processes:Record<string,{name:string}[]>;canEdit:boolean}
type OnboardingStatus='not_required'|'pending'|'probation'|'passed'|'failed'
type ExtendedProfile=EmployeeProfile&{onboarding_status?:OnboardingStatus;review_date?:string|null;onboarding_note?:string|null}
type SkillDraft={proficiency:number;efficiency_percent:number;qualification_status:QualificationStatus;is_primary:boolean}
const statusLabels:Record<QualificationStatus,string>={qualified:'ทำได้',training:'ฝึกงาน',blocked:'มือใหม่'}
const onboardingLabels:Record<OnboardingStatus,string>={not_required:'ไม่ต้องประเมิน',pending:'รอประเมิน',probation:'ทดลองงาน',passed:'ผ่านงาน',failed:'ไม่ผ่านงาน'}
const employeeName=(e:ManpowerEmployee)=>e.nickname||`${e.first_name} ${e.last_name}`
const employeeFullName=(e:ManpowerEmployee)=>`${e.first_name} ${e.last_name}`.trim()
const defaultDraft:SkillDraft={proficiency:1,efficiency_percent:100,qualification_status:'blocked',is_primary:false}

function SkillOverview({groups,skills}:{groups:Record<string,EmployeeSkill[]>;skills:EmployeeSkill[]}){
 const qualified=skills.filter(s=>s.qualification_status==='qualified').length
 const training=skills.filter(s=>s.qualification_status==='training').length
 const primary=skills.filter(s=>s.is_primary).length
 return <div className="rounded-xl border bg-white p-5 shadow-sm">
  <div className="flex flex-wrap items-start justify-between gap-3">
   <div><h3 className="font-semibold text-slate-900">ภาพรวมทักษะที่มี</h3><p className="text-xs text-gray-500">ดูระดับความชำนาญและประสิทธิภาพของพนักงานคนนี้แบบรวดเร็ว</p></div>
   <div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-blue-50 px-2.5 py-1 font-semibold text-blue-700">ทั้งหมด {skills.length}</span><span className="rounded-full bg-emerald-50 px-2.5 py-1 font-semibold text-emerald-700">ทำได้ {qualified}</span><span className="rounded-full bg-amber-50 px-2.5 py-1 font-semibold text-amber-700">ฝึกงาน {training}</span><span className="rounded-full bg-violet-50 px-2.5 py-1 font-semibold text-violet-700">งานหลัก {primary}</span></div>
  </div>
  {skills.length===0?<div className="mt-4 rounded-xl border border-dashed bg-gray-50 px-4 py-8 text-center text-sm text-gray-400">ยังไม่มีทักษะที่ตั้งค่าไว้</div>:<div className="mt-4 grid gap-3 xl:grid-cols-2">{Object.entries(groups).map(([department,items])=><section key={department} className="overflow-hidden rounded-xl border border-slate-200"><div className="flex items-center justify-between bg-slate-50 px-4 py-2.5"><b className="text-sm text-blue-700">{department}</b><span className="text-xs text-gray-500">{items.length} ทักษะ</span></div><div className="divide-y divide-slate-100">{items.map(skill=><div key={`${skill.department_name}|${skill.process_name}`} className="p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-1.5"><b className="truncate text-sm text-slate-800">{skill.process_name}</b>{skill.is_primary&&<span className="rounded bg-violet-100 px-1.5 py-0.5 text-[10px] font-semibold text-violet-700">งานหลัก</span>}</div><span className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-[10px] font-semibold ${skill.qualification_status==='qualified'?'bg-emerald-100 text-emerald-700':skill.qualification_status==='training'?'bg-amber-100 text-amber-700':'bg-red-100 text-red-700'}`}>{statusLabels[skill.qualification_status]}</span></div><div className="shrink-0 text-right"><b className="text-lg text-blue-700">S{skill.proficiency}</b><div className="text-[11px] text-gray-500">{Number(skill.efficiency_percent)}%</div></div></div><div className="mt-2 flex gap-1" aria-label={`Skill ${skill.proficiency} จาก 5`}>{[1,2,3,4,5].map(level=><span key={level} className={`h-1.5 flex-1 rounded-full ${level<=skill.proficiency?'bg-blue-500':'bg-slate-200'}`}/>)}</div></div>)}</div></section>)}</div>}
 </div>
}

export default function EmployeeSkillsPanel({departments,processes,canEdit}:Props){
 const [employees,setEmployees]=useState<ManpowerEmployee[]>([]),[profiles,setProfiles]=useState<ExtendedProfile[]>([]),[skills,setSkills]=useState<EmployeeSkill[]>([])
 const [selectedId,setSelectedId]=useState(''),[search,setSearch]=useState(''),[deptFilter,setDeptFilter]=useState('ALL'),[employeeDeptFilter,setEmployeeDeptFilter]=useState('ALL'),[employeeFilter,setEmployeeFilter]=useState<'all'|'new'|'configured'|'unconfigured'>('all')
 const [onboardingNote,setOnboardingNote]=useState('')
 const [subView,setSubView]=useState<'skills'|'evaluation'>('skills')
 const [drafts,setDrafts]=useState<Record<string,SkillDraft>>({}),[dirty,setDirty]=useState<Set<string>>(new Set()),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');const [er,pr,sr]=await Promise.all([
  supabase.from('hr_employees').select('id,employee_code,first_name,last_name,nickname,employment_status,hire_date,department:hr_departments!hr_employees_department_id_fkey(name),position:hr_positions!hr_employees_position_id_fkey(name)').in('employment_status',['active','probation']).order('employee_code'),
  supabase.from('plan_employee_profiles').select('*'),supabase.from('plan_employee_skills').select('*').order('department_name').order('process_name')])
  const err=er.error||pr.error||sr.error;if(err)setError(err.message.includes('onboarding_status')?'กรุณารัน migration 350_plan_employee_onboarding.sql ก่อนใช้งานการประเมินพนักงานใหม่':err.message)
  const emp=(er.data||[]) as unknown as ManpowerEmployee[];setEmployees(emp);setProfiles((pr.data||[]) as ExtendedProfile[]);setSkills((sr.data||[]) as EmployeeSkill[]);setSelectedId(id=>id||emp[0]?.id||'');setLoading(false)},[])
 useEffect(()=>{void load()},[load])
 const skillMap=useMemo(()=>new Map(skills.map(s=>[`${s.employee_id}|${s.department_name}|${s.process_name}`,s])),[skills])
 const selected=employees.find(e=>e.id===selectedId),profile=profiles.find(p=>p.employee_id===selectedId)
 useEffect(()=>{setOnboardingNote(profile?.onboarding_note||'')},[selectedId,profile?.onboarding_note])
 const employeeDepartments=useMemo(()=>[...new Set(employees.map(e=>e.department?.name).filter((name):name is string=>Boolean(name)))].sort((a,b)=>a.localeCompare(b,'th')),[employees])
 const filteredEmployees=employees.filter(e=>{const text=`${e.employee_code} ${e.nickname||''} ${e.first_name} ${e.last_name} ${e.position?.name||''} ${e.department?.name||''}`.toLowerCase();if(!text.includes(search.toLowerCase()))return false;if(employeeDeptFilter!=='ALL'&&e.department?.name!==employeeDeptFilter)return false;const count=skills.filter(s=>s.employee_id===e.id).length;const p=profiles.find(x=>x.employee_id===e.id);if(employeeFilter==='new')return e.employment_status==='probation'||['pending','probation'].includes(p?.onboarding_status||'');if(employeeFilter==='configured')return count>0;if(employeeFilter==='unconfigured')return count===0;return true})
 const qualifiedEmployeeCount=new Set(skills.filter(s=>s.qualification_status==='qualified').map(s=>s.employee_id)).size
 const trainingEmployeeCount=new Set(skills.filter(s=>s.qualification_status==='training').map(s=>s.employee_id)).size
 const productionEmployeeCount=employees.filter(e=>profiles.find(p=>p.employee_id===e.id)?.is_available_for_planning!==false).length
 const operations=departments.flatMap(dept=>(processes[dept]||[]).map(p=>({dept,process:p.name}))).filter(x=>deptFilter==='ALL'||x.dept===deptFilter)
 const selectedSkills=useMemo(()=>skills.filter(s=>s.employee_id===selectedId).sort((a,b)=>a.department_name.localeCompare(b.department_name,'th')||b.proficiency-a.proficiency||a.process_name.localeCompare(b.process_name,'th')),[skills,selectedId])
 const selectedSkillGroups=useMemo(()=>selectedSkills.reduce<Record<string,EmployeeSkill[]>>((groups,skill)=>{(groups[skill.department_name]??=[]).push(skill);return groups},{}),[selectedSkills])
 function draftFor(dept:string,process:string){const key=`${dept}|${process}`;return drafts[key]||skillMap.get(`${selectedId}|${key}`)||defaultDraft}
 function updateDraft(dept:string,process:string,patch:Partial<SkillDraft>){const key=`${dept}|${process}`;setDrafts(d=>({...d,[key]:{...draftFor(dept,process),...patch}}));setDirty(d=>new Set(d).add(key));setMessage('')}
 async function saveDirty(){if(!selectedId||dirty.size===0)return;setSaving(true);setError('');const rows=[...dirty].map(key=>{const [department_name,process_name]=key.split('|');return{employee_id:selectedId,department_name,process_name,...drafts[key]}});const {error:e}=await supabase.from('plan_employee_skills').upsert(rows,{onConflict:'employee_id,department_name,process_name'});setSaving(false);if(e)setError(e.message);else{setMessage(`บันทึก ${rows.length} ทักษะแล้ว`);setDirty(new Set());setDrafts({});await load()}}
 async function saveProfile(patch:Partial<ExtendedProfile>){if(!selectedId)return;const {error:e}=await supabase.from('plan_employee_profiles').upsert({employee_id:selectedId,responsibility_level:profile?.responsibility_level||'operator',is_available_for_planning:profile?.is_available_for_planning??true,onboarding_status:profile?.onboarding_status||'not_required',review_date:profile?.review_date||null,onboarding_note:profile?.onboarding_note||null,...patch},{onConflict:'employee_id'});if(e)setError(e.message);else await load()}
 if(loading)return <div className="rounded-xl border bg-white p-12 text-center text-gray-500">กำลังโหลด Skill Matrix...</div>
 const subNav=<div className="flex gap-2 rounded-xl border bg-white p-2 shadow-sm"><button className={`rounded-lg px-4 py-2 text-sm font-semibold ${subView==='skills'?'bg-blue-600 text-white':'text-gray-600 hover:bg-gray-100'}`} onClick={()=>setSubView('skills')}>Skill Matrix</button><button className={`rounded-lg px-4 py-2 text-sm font-semibold ${subView==='evaluation'?'bg-blue-600 text-white':'text-gray-600 hover:bg-gray-100'}`} onClick={()=>setSubView('evaluation')}>ประเมินพนักงานใหม่</button></div>
 if(subView==='evaluation')return <section className="employee-skills-page space-y-4"><div className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">ทักษะและการประเมินพนักงาน</h2><p className="text-sm text-gray-500">บันทึกผลติดตามพนักงานใหม่แบบรายวันและรายสัปดาห์</p></div>{subNav}<NewEmployeeEvaluationPanel canEdit={canEdit}/></section>
 return <section className="employee-skills-page space-y-4"><div className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">ทักษะพนักงาน</h2><p className="text-sm text-gray-500">เลือกพนักงานหนึ่งคน แล้วกำหนดความสามารถทุกกระบวนการจากหน้าเดียว ระบบจะอัปเดตรายการเดิมและไม่สร้างทักษะซ้ำ</p></div><div className="flex flex-wrap gap-2 text-sm"><span className="rounded-full bg-slate-100 px-3 py-1.5 font-semibold text-slate-700">จำนวนรวม {employees.length} คน</span><span className="rounded-full bg-emerald-100 px-3 py-1.5 font-semibold text-emerald-700">มีทักษะ {qualifiedEmployeeCount} คน</span><span className="rounded-full bg-amber-100 px-3 py-1.5 font-semibold text-amber-700">ฝึกงาน {trainingEmployeeCount} คน</span><span className="rounded-full bg-blue-100 px-3 py-1.5 font-semibold text-blue-700">ฝ่ายผลิต {productionEmployeeCount} คน</span></div></div>{error&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message&&<p className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}</div>{subNav}
 <div className="grid min-h-[650px] gap-4 lg:grid-cols-[360px_minmax(0,1fr)]"><aside className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="space-y-3 border-b p-4"><input className="w-full rounded-lg border px-3 py-2" placeholder="ค้นหารหัส ชื่อจริง นามสกุล ชื่อเล่น" value={search} onChange={e=>setSearch(e.target.value)}/><select className="w-full rounded-lg border px-3 py-2" value={employeeDeptFilter} onChange={e=>setEmployeeDeptFilter(e.target.value)}><option value="ALL">ทุกแผนก</option>{employeeDepartments.map(name=><option key={name} value={name}>{name}</option>)}</select><select className="w-full rounded-lg border px-3 py-2" value={employeeFilter} onChange={e=>setEmployeeFilter(e.target.value as typeof employeeFilter)}><option value="all">พนักงานทั้งหมด</option><option value="new">พนักงานใหม่/ทดลองงาน</option><option value="configured">ตั้งค่าทักษะแล้ว</option><option value="unconfigured">ยังไม่มีทักษะ</option></select><p className="text-xs text-gray-500">พบ {filteredEmployees.length} คน</p></div><div className="max-h-[570px] overflow-y-auto">{filteredEmployees.map(e=>{const count=skills.filter(s=>s.employee_id===e.id).length;return <button key={e.id} onClick={()=>{setSelectedId(e.id);setDrafts({});setDirty(new Set());setMessage('')}} className={`w-full border-b p-3 text-left hover:bg-blue-50 ${selectedId===e.id?'bg-blue-50 ring-1 ring-inset ring-blue-200':''}`}><div className="flex justify-between gap-2"><b>{e.employee_code} · {e.nickname||'-'}</b><span className={`shrink-0 rounded-full px-2 py-0.5 text-xs ${count?'bg-emerald-100 text-emerald-700':'bg-gray-100 text-gray-500'}`}>{count} ทักษะ</span></div><p className="mt-1 text-sm font-medium text-slate-700">{employeeFullName(e)}</p><p className="mt-1 text-xs text-gray-500">ตำแหน่ง: {e.position?.name||'ไม่ระบุ'}</p><p className="text-xs text-gray-500">แผนก: {e.department?.name||'ไม่ระบุ'}</p></button>})}</div></aside>
 <main className="min-w-0 space-y-4">{selected&&<><div className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-bold">{selected.employee_code} · {employeeName(selected)}</h3><p className="text-sm text-gray-500">{selected.position?.name||'ไม่ระบุตำแหน่ง'} · {selected.department?.name||'ไม่ระบุแผนก'}</p></div><label className={`flex min-w-[190px] items-center justify-between gap-3 rounded-xl border px-3 py-2.5 text-sm transition ${profile?.is_available_for_planning!==false?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-gray-200 bg-gray-50 text-gray-500'} ${canEdit?'cursor-pointer':'cursor-not-allowed opacity-70'}`}><span><b className="block">ใช้จัดแผนการผลิต</b><span className="text-xs">{profile?.is_available_for_planning!==false?'เปิดใช้งาน':'ปิดใช้งาน'}</span></span><span className={`relative h-7 w-12 shrink-0 rounded-full transition-colors ${profile?.is_available_for_planning!==false?'bg-emerald-500':'bg-gray-300'}`}><input type="checkbox" className="sr-only" checked={profile?.is_available_for_planning!==false} disabled={!canEdit} onChange={e=>saveProfile({is_available_for_planning:e.target.checked})}/><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow-sm transition-transform ${profile?.is_available_for_planning!==false?'translate-x-6':'translate-x-1'}`}/></span></label></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label><span className="mb-1 block text-xs font-medium">ระดับหน้าที่</span><select className="w-full rounded-lg border px-3 py-2" value={profile?.responsibility_level||'operator'} disabled={!canEdit} onChange={e=>saveProfile({responsibility_level:e.target.value as ResponsibilityLevel})}>{Object.entries(RESPONSIBILITY_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><span className="mb-1 block text-xs font-medium">ผลประเมินพนักงานใหม่</span><select className="w-full rounded-lg border px-3 py-2" value={profile?.onboarding_status||'not_required'} disabled={!canEdit} onChange={e=>saveProfile({onboarding_status:e.target.value as OnboardingStatus})}>{Object.entries(onboardingLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><span className="mb-1 block text-xs font-medium">วันที่ประเมิน/ครบกำหนด</span><input type="date" className="w-full rounded-lg border px-3 py-2" value={profile?.review_date||''} disabled={!canEdit} onChange={e=>saveProfile({review_date:e.target.value||null})}/></label><label><span className="mb-1 block text-xs font-medium">หมายเหตุการประเมิน</span><input className="w-full rounded-lg border px-3 py-2" value={onboardingNote} disabled={!canEdit} onChange={e=>setOnboardingNote(e.target.value)} onBlur={()=>saveProfile({onboarding_note:onboardingNote})}/></label></div></div><SkillOverview groups={selectedSkillGroups} skills={selectedSkills}/>
 <div className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h3 className="font-semibold">Skill Matrix รายกระบวนการ</h3><p className="text-xs text-gray-500">แก้หลายรายการแล้วกด “บันทึกที่เปลี่ยน” ครั้งเดียว</p></div><div className="flex gap-2"><select className="rounded-lg border px-3 py-2 text-sm" value={deptFilter} onChange={e=>setDeptFilter(e.target.value)}><option value="ALL">ทุกแผนก</option>{departments.map(d=><option key={d}>{d}</option>)}</select><button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" disabled={!canEdit||saving||dirty.size===0} onClick={saveDirty}>{saving?'กำลังบันทึก...':`บันทึกที่เปลี่ยน (${dirty.size})`}</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-3">แผนก</th><th>กระบวนการ</th><th>สถานะ</th><th>Skill</th><th>ประสิทธิภาพ</th><th>งานหลัก</th><th>ข้อมูลเดิม</th></tr></thead><tbody>{operations.map(o=>{const key=`${o.dept}|${o.process}`,draft=draftFor(o.dept,o.process),existing=skillMap.get(`${selectedId}|${key}`);return <tr key={key} className={`border-t ${dirty.has(key)?'bg-amber-50':''}`}><td className="p-3 font-semibold text-blue-700">{o.dept}</td><td>{o.process}</td><td><select className="rounded border px-2 py-1" value={draft.qualification_status} disabled={!canEdit} onChange={e=>updateDraft(o.dept,o.process,{qualification_status:e.target.value as QualificationStatus})}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td><select className="rounded border px-2 py-1" value={draft.proficiency} disabled={!canEdit} onChange={e=>updateDraft(o.dept,o.process,{proficiency:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></td><td><div className="flex items-center gap-1"><input className="w-20 rounded border px-2 py-1" type="number" min="1" max="300" value={draft.efficiency_percent} disabled={!canEdit} onChange={e=>updateDraft(o.dept,o.process,{efficiency_percent:Number(e.target.value)})}/><span>%</span></div></td><td><input type="checkbox" checked={draft.is_primary} disabled={!canEdit} onChange={e=>updateDraft(o.dept,o.process,{is_primary:e.target.checked})}/></td><td>{existing?<span className="text-emerald-700">ตั้งค่าแล้ว</span>:<span className="text-gray-400">ยังไม่ตั้งค่า</span>}</td></tr>})}</tbody></table></div></div></>}</main></div></section>
}
