import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabase'
import { RESPONSIBILITY_LABELS, isSkillUsable, manpowerScore, type EmployeeProfile, type EmployeeSkill, type ManpowerEmployee, type OperationRequirement, type QualificationStatus, type ResponsibilityLevel } from '../../lib/planManpower'

type WorkOrderSummary={id:string;name:string;departments:string[];lineAssignments:Record<string,number>}
type Props={mode:'overview'|'settings';departments:string[];processes:Record<string,{name:string}[]>;selectedDate:string;canEdit:boolean;workOrders?:WorkOrderSummary[]}
const qLabels:Record<QualificationStatus,string>={qualified:'ทำได้',training:'ฝึกงาน',blocked:'มือใหม่'}
const empName=(e:ManpowerEmployee)=>e.nickname||`${e.first_name} ${e.last_name}`

export default function ManpowerPanel({mode,departments,processes,selectedDate,canEdit,workOrders=[]}:Props){
 const [employees,setEmployees]=useState<ManpowerEmployee[]>([]),[profiles,setProfiles]=useState<EmployeeProfile[]>([]),[skills,setSkills]=useState<EmployeeSkill[]>([])
 const [requirements,setRequirements]=useState<OperationRequirement[]>([])
 const [leaves,setLeaves]=useState<Set<string>>(new Set()),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 const [employeeId,setEmployeeId]=useState(''),[department,setDepartment]=useState(departments[0]||''),[processName,setProcessName]=useState('')
 const [requirementDept,setRequirementDept]=useState('ALL')
 const [proficiency,setProficiency]=useState(3),[efficiency,setEfficiency]=useState(100),[qualification,setQualification]=useState<QualificationStatus>('qualified')
 useEffect(()=>{const first=processes[department]?.[0]?.name||'';if(!processes[department]?.some(p=>p.name===processName))setProcessName(first)},[department,processes,processName])
 const load=useCallback(async()=>{setLoading(true);setError('');const [er,pr,sr,rr,lr]=await Promise.all([
  supabase.from('hr_employees').select('id,employee_code,first_name,last_name,nickname,employment_status,department:hr_departments!hr_employees_department_id_fkey(name),position:hr_positions!hr_employees_position_id_fkey(name)').in('employment_status',['active','probation']).order('employee_code'),
  supabase.from('plan_employee_profiles').select('*'),supabase.from('plan_employee_skills').select('*').order('department_name').order('process_name'),
  supabase.from('plan_operation_requirements').select('*').order('department_name').order('process_name'),
  supabase.from('hr_leave_requests').select('employee_id').eq('status','approved').lte('start_date',selectedDate).gte('end_date',selectedDate)])
  const err=er.error||pr.error||sr.error||rr.error||lr.error;if(err)setError(err.message.includes('plan_employee_')?'ยังไม่ได้ติดตั้งฐานข้อมูลกำลังคน กรุณารัน migration 349_plan_manpower.sql':err.message)
  setEmployees((er.data||[]) as unknown as ManpowerEmployee[]);setProfiles((pr.data||[]) as EmployeeProfile[]);setSkills((sr.data||[]) as EmployeeSkill[]);setRequirements((rr.data||[]) as OperationRequirement[]);setLeaves(new Set((lr.data||[]).map(x=>x.employee_id)));setLoading(false)},[selectedDate])
 useEffect(()=>{void load()},[load])
 const profileMap=useMemo(()=>new Map(profiles.map(p=>[p.employee_id,p])),[profiles])
 const available=employees.filter(e=>profileMap.get(e.id)?.is_available_for_planning!==false&&!leaves.has(e.id))
 const coverage=departments.flatMap(dept=>(processes[dept]||[]).map(proc=>{const requirement=requirements.find(r=>r.department_name===dept&&r.process_name===proc.name)||{required_workers:1,minimum_proficiency:1,required_supervisors:0};const eligible=skills.filter(s=>s.department_name===dept&&s.process_name===proc.name&&s.proficiency>=requirement.minimum_proficiency&&isSkillUsable(s,selectedDate)&&available.some(e=>e.id===s.employee_id));const supervisors=eligible.filter(s=>['supervisor','lead'].includes(profileMap.get(s.employee_id)?.responsibility_level||''));const shortage=Math.max(0,requirement.required_workers-eligible.length),supervisorShortage=Math.max(0,requirement.required_supervisors-supervisors.length);return{dept,process:proc.name,eligible,requirement,shortage,supervisorShortage,risk:shortage>0||supervisorShortage>0?'ขาดคน':eligible.length===requirement.required_workers?'พอดี':'พร้อม'}}))
 async function saveSkill(){if(!employeeId||!department||!processName)return;setSaving(true);const {error:e}=await supabase.from('plan_employee_skills').upsert({employee_id:employeeId,department_name:department,process_name:processName,proficiency,efficiency_percent:efficiency,qualification_status:qualification,assessed_at:selectedDate},{onConflict:'employee_id,department_name,process_name'});setSaving(false);if(e)setError(e.message);else await load()}
 async function updateProfile(id:string,patch:Partial<EmployeeProfile>){const p=profileMap.get(id);const {error:e}=await supabase.from('plan_employee_profiles').upsert({employee_id:id,responsibility_level:p?.responsibility_level||'operator',is_available_for_planning:p?.is_available_for_planning??true,...patch},{onConflict:'employee_id'});if(e)setError(e.message);else await load()}
 async function updateRequirement(dept:string,process:string,patch:Partial<OperationRequirement>){const current=requirements.find(r=>r.department_name===dept&&r.process_name===process);const {error:e}=await supabase.from('plan_operation_requirements').upsert({department_name:dept,process_name:process,required_workers:current?.required_workers||1,minimum_proficiency:current?.minimum_proficiency||1,required_supervisors:current?.required_supervisors||0,...patch},{onConflict:'department_name,process_name'});if(e)setError(e.message);else await load()}
 if(loading)return <div className="rounded-xl border bg-white p-10 text-center text-gray-500">กำลังโหลดข้อมูลกำลังคน...</div>
 if(mode==='overview')return <section className="space-y-4">
  <div className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">กำลังคนตามใบงาน</h2><p className="text-sm text-gray-500">แสดงผู้ที่มีคุณสมบัติเหมาะสมสำหรับใบงานวันที่ {selectedDate} — ยังไม่ใช่การมอบหมายตัวจริง</p></div><div className="flex gap-2 text-sm"><span className="rounded-lg bg-emerald-50 px-3 py-2 text-emerald-700">พร้อม {available.length} คน</span><span className="rounded-lg bg-amber-50 px-3 py-2 text-amber-700">ลา {leaves.size} คน</span></div></div>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div>
  {workOrders.length===0?<div className="rounded-xl border border-dashed bg-white p-12 text-center text-gray-500"><p className="font-semibold">ไม่มีใบงานในวันที่เลือก</p><p className="mt-1 text-sm">เมื่อมีใบงาน ระบบจะแสดงความต้องการกำลังคนแยกตามใบงานและกระบวนการที่นี่</p></div>:workOrders.map(job=>{
   const rows=coverage.filter(r=>job.departments.includes(r.dept));const shortageCount=rows.reduce((n,r)=>n+r.shortage+r.supervisorShortage,0)
   return <article key={job.id} className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b bg-slate-50 px-5 py-4"><div><h3 className="text-lg font-bold text-slate-900">{job.name}</h3><p className="text-xs text-gray-500">ใบงาน {job.id}</p></div><span className={`rounded-full px-3 py-1 text-sm font-semibold ${shortageCount?'bg-red-100 text-red-700':'bg-emerald-100 text-emerald-700'}`}>{shortageCount?`ขาดรวม ${shortageCount} ตำแหน่ง`:'กำลังคนครอบคลุม'}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-white text-left text-gray-500"><tr><th className="p-3">แผนก / ไลน์</th><th>กระบวนการ</th><th>ต้องการ</th><th>คนที่ผ่านเกณฑ์</th><th>ผู้ที่ระบบแนะนำ</th><th>สถานะ</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.dept}-${r.process}`} className="border-t"><td className="p-3 font-semibold">{r.dept} · L{(job.lineAssignments[r.dept]??0)+1}</td><td>{r.process}<p className="text-xs text-gray-400">Skill ≥ {r.requirement.minimum_proficiency}</p></td><td>{r.requirement.required_workers} คน{r.requirement.required_supervisors>0&&<p className="text-xs text-gray-500">หัวหน้า {r.requirement.required_supervisors}</p>}</td><td>{r.eligible.length} คน</td><td><div className="flex flex-wrap gap-1">{r.eligible.sort((a,b)=>manpowerScore(b)-manpowerScore(a)).slice(0,r.requirement.required_workers).map(s=>{const emp=employees.find(e=>e.id===s.employee_id);return emp?<span key={s.employee_id} className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-700">{empName(emp)} · S{s.proficiency}</span>:null})}{r.eligible.length===0&&<span className="text-red-600">ไม่มีผู้เหมาะสม</span>}</div></td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${r.risk==='พร้อม'?'bg-emerald-100 text-emerald-700':r.risk==='พอดี'?'bg-amber-100 text-amber-700':'bg-red-100 text-red-700'}`}>{r.shortage?`ขาด ${r.shortage} คน`:r.supervisorShortage?`ขาดหัวหน้า ${r.supervisorShortage}`:r.risk}</span></td></tr>)}</tbody></table></div></article>
  })}
 </section>
 if(mode==='settings')return <section className="space-y-4">
  <div className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">ตั้งค่าความต้องการกำลังคน</h2><p className="text-sm text-gray-500">กำหนดจำนวนคนและระดับขั้นต่ำที่แต่ละกระบวนการต้องใช้ สำหรับข้อมูลรายบุคคลให้ไปที่แถบ “ทักษะพนักงาน”</p>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div>
  <div className="overflow-x-auto rounded-xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h3 className="font-semibold">จำนวนคนที่ต้องการต่อกระบวนการ</h3><p className="text-xs text-gray-500">ใช้ตรวจคนขาดและความพร้อมก่อนเพิ่มไลน์ผลิต</p></div><select className="rounded-lg border px-3 py-2 text-sm" value={requirementDept} onChange={e=>setRequirementDept(e.target.value)}><option value="ALL">ทุกแผนก</option>{departments.map(d=><option key={d}>{d}</option>)}</select></div><table className="w-full min-w-[720px] text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-3">แผนก / กระบวนการ</th><th>จำนวนคน</th><th>Skill ขั้นต่ำ</th><th>หัวหน้า/ผู้เชี่ยวชาญ</th></tr></thead><tbody>{coverage.filter(r=>requirementDept==='ALL'||r.dept===requirementDept).map(r=><tr key={`${r.dept}-${r.process}`} className="border-t"><td className="p-3"><b>{r.dept}</b> · {r.process}</td><td><input className="w-20 rounded border px-2 py-1" type="number" min="1" value={r.requirement.required_workers} disabled={!canEdit} onChange={e=>updateRequirement(r.dept,r.process,{required_workers:Number(e.target.value)})}/></td><td><select className="rounded border px-2 py-1" value={r.requirement.minimum_proficiency} disabled={!canEdit} onChange={e=>updateRequirement(r.dept,r.process,{minimum_proficiency:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></td><td><input className="w-20 rounded border px-2 py-1" type="number" min="0" value={r.requirement.required_supervisors} disabled={!canEdit} onChange={e=>updateRequirement(r.dept,r.process,{required_supervisors:Number(e.target.value)})}/></td></tr>)}</tbody></table></div>
 </section>
 return <section className="space-y-4">
  <div className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">ตั้งค่ากำลังคนและ Skill Matrix</h2><p className="text-sm text-gray-500">รายชื่อพนักงานเชื่อมจาก HR โดยตรง</p>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-lg bg-blue-50 p-3"><b className="text-blue-800">1. กำหนดความต้องการ</b><p className="mt-1 text-xs text-blue-700">ระบุว่ากระบวนการหนึ่งต้องใช้กี่คน Skill ขั้นต่ำเท่าไร</p></div><div className="rounded-lg bg-violet-50 p-3"><b className="text-violet-800">2. เพิ่มทักษะพนักงาน</b><p className="mt-1 text-xs text-violet-700">เลือกพนักงาน แผนก กระบวนการ Skill และประสิทธิภาพ แล้วกดบันทึก</p></div><div className="rounded-lg bg-emerald-50 p-3"><b className="text-emerald-800">3. ตรวจผล</b><p className="mt-1 text-xs text-emerald-700">กลับหน้า “กำลังคน” เพื่อดูคนขาดและรายชื่อที่แนะนำแยกตามใบงาน</p></div></div></div>
  <div className="rounded-xl border bg-white p-5 shadow-sm">
   <h3 className="font-semibold">2. เพิ่มหรือแก้ไขทักษะพนักงาน</h3>
   <div className="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-6">
    <label className="xl:col-span-2"><span className="mb-1 block text-sm font-medium">พนักงาน</span><select className="w-full rounded-lg border px-3 py-2" value={employeeId} onChange={e=>setEmployeeId(e.target.value)} disabled={!canEdit}><option value="">เลือกพนักงาน</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employee_code} · {empName(e)} · {e.position?.name||'ไม่ระบุตำแหน่ง'}</option>)}</select></label>
    <label><span className="mb-1 block text-sm font-medium">แผนกที่ทำได้</span><select className="w-full rounded-lg border px-3 py-2" value={department} onChange={e=>setDepartment(e.target.value)}>{departments.map(d=><option key={d}>{d}</option>)}</select></label>
    <label><span className="mb-1 block text-sm font-medium">กระบวนการที่ทำได้</span><select className="w-full rounded-lg border px-3 py-2" value={processName} onChange={e=>setProcessName(e.target.value)}>{(processes[department]||[]).map(p=><option key={p.name}>{p.name}</option>)}</select></label>
    <label><span className="mb-1 block text-sm font-medium">ระดับความชำนาญ</span><select className="w-full rounded-lg border px-3 py-2" value={proficiency} onChange={e=>setProficiency(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>Skill {n}</option>)}</select></label>
    <label><span className="mb-1 block text-sm font-medium">ประสิทธิภาพเทียบมาตรฐาน (%)</span><input className="w-full rounded-lg border px-3 py-2" type="number" min="1" max="300" value={efficiency} onChange={e=>setEfficiency(Number(e.target.value))}/><span className="mt-1 block text-xs text-gray-500">100% = ทำได้ตามเวลามาตรฐาน</span></label>
   </div>
   <div className="mt-4 flex flex-col gap-3 rounded-lg bg-gray-50 p-3 lg:flex-row lg:items-end">
    <label className="min-w-[220px]"><span className="mb-1 block text-sm font-medium">สถานะการนำไปจัดงาน</span><select className="w-full rounded-lg border bg-white px-3 py-2" value={qualification} onChange={e=>setQualification(e.target.value as QualificationStatus)}>{Object.entries(qLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    <div className="grid flex-1 gap-2 text-xs sm:grid-cols-3"><p><b className="text-emerald-700">ทำได้</b> — ระบบเลือกเป็นกำลังหลักได้</p><p><b className="text-amber-700">ฝึกงาน</b> — อยู่ระหว่างเรียนรู้ ไม่ใช้เป็นกำลังหลัก</p><p><b className="text-red-700">มือใหม่</b> — ยังทำกระบวนการนี้ไม่ได้ ระบบจะไม่เลือกจัดงาน</p></div>
    <button className="rounded-lg bg-blue-600 px-5 py-2 font-semibold text-white disabled:opacity-50" onClick={saveSkill} disabled={!canEdit||saving||!employeeId}>{saving?'กำลังบันทึก...':'บันทึกทักษะ'}</button>
   </div>
  </div>
  <div className="overflow-x-auto rounded-xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h3 className="font-semibold">1. จำนวนคนที่ต้องการต่อกระบวนการ</h3><p className="text-xs text-gray-500">ใช้ตรวจคนขาดและความพร้อมก่อนเพิ่มไลน์ผลิต</p></div><select className="rounded-lg border px-3 py-2 text-sm" value={requirementDept} onChange={e=>setRequirementDept(e.target.value)}><option value="ALL">ทุกแผนก</option>{departments.map(d=><option key={d}>{d}</option>)}</select></div><table className="w-full min-w-[720px] text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-3">แผนก / กระบวนการ</th><th>จำนวนคน</th><th>Skill ขั้นต่ำ</th><th>หัวหน้า/ผู้เชี่ยวชาญ</th></tr></thead><tbody>{coverage.filter(r=>requirementDept==='ALL'||r.dept===requirementDept).map(r=><tr key={`${r.dept}-${r.process}`} className="border-t"><td className="p-3"><b>{r.dept}</b> · {r.process}</td><td><input className="w-20 rounded border px-2 py-1" type="number" min="1" value={r.requirement.required_workers} disabled={!canEdit} onChange={e=>updateRequirement(r.dept,r.process,{required_workers:Number(e.target.value)})}/></td><td><select className="rounded border px-2 py-1" value={r.requirement.minimum_proficiency} disabled={!canEdit} onChange={e=>updateRequirement(r.dept,r.process,{minimum_proficiency:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></td><td><input className="w-20 rounded border px-2 py-1" type="number" min="0" value={r.requirement.required_supervisors} disabled={!canEdit} onChange={e=>updateRequirement(r.dept,r.process,{required_supervisors:Number(e.target.value)})}/></td></tr>)}</tbody></table></div>
  <div className="overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="w-full min-w-[900px] text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-3">พนักงาน</th><th>ระดับหน้าที่</th><th>ใช้จัดแผน</th><th>ทักษะ</th></tr></thead><tbody>{employees.map(e=>{const p=profileMap.get(e.id),own=skills.filter(s=>s.employee_id===e.id);return <tr key={e.id} className="border-t align-top"><td className="p-3"><p className="font-semibold">{e.employee_code} · {empName(e)}</p><p className="text-xs text-gray-500">{e.department?.name||'-'} / {e.position?.name||'-'}</p></td><td className="py-3"><select className="rounded border px-2 py-1" value={p?.responsibility_level||'operator'} disabled={!canEdit} onChange={x=>updateProfile(e.id,{responsibility_level:x.target.value as ResponsibilityLevel})}>{Object.entries(RESPONSIBILITY_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td className="py-3"><input type="checkbox" checked={p?.is_available_for_planning!==false} disabled={!canEdit} onChange={x=>updateProfile(e.id,{is_available_for_planning:x.target.checked})}/></td><td className="py-3 pr-3"><div className="flex flex-wrap gap-1">{own.length?own.map(s=><span key={s.id} className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-700">{s.department_name} · {s.process_name} · S{s.proficiency} · {s.efficiency_percent}%</span>):<span className="text-gray-400">ยังไม่มีทักษะ</span>}</div></td></tr>})}</tbody></table></div>
 </section>
}
