import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabase'
import type { ManpowerEmployee } from '../../lib/planManpower'

type OnboardingStatus='not_required'|'pending'|'probation'|'passed'|'failed'
type Evaluation={id:string;employee_id:string;period_type:'daily'|'weekly';evaluation_date:string;period_start:string;period_end:string;attendance_score:number;learning_score:number;quality_score:number;teamwork_score:number;discipline_score:number;result:'continue'|'passed'|'failed';strengths?:string;improvements?:string;note?:string;created_at:string}
type Employee=ManpowerEmployee&{hire_date?:string|null}
type Props={canEdit:boolean}
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const fullName=(e:Employee)=>`${e.first_name} ${e.last_name}`.trim()
const statusLabels:Record<OnboardingStatus,string>={not_required:'ไม่ต้องประเมิน',pending:'รอประเมิน',probation:'ทดลองงาน',passed:'ผ่านงาน',failed:'ไม่ผ่านงาน'}
const resultLabels={continue:'ประเมินต่อ',passed:'ผ่านงาน',failed:'ไม่ผ่านงาน'}

export default function NewEmployeeEvaluationPanel({canEdit}:Props){
 const [employees,setEmployees]=useState<Employee[]>([]),[profiles,setProfiles]=useState<any[]>([]),[evaluations,setEvaluations]=useState<Evaluation[]>([]),[selectedId,setSelectedId]=useState(''),[search,setSearch]=useState(''),[showAll,setShowAll]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const [periodType,setPeriodType]=useState<'daily'|'weekly'>('daily'),[date,setDate]=useState(localDate()),[scores,setScores]=useState({attendance:3,learning:3,quality:3,teamwork:3,discipline:3}),[result,setResult]=useState<'continue'|'passed'|'failed'>('continue'),[strengths,setStrengths]=useState(''),[improvements,setImprovements]=useState(''),[note,setNote]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');const [er,pr,vr]=await Promise.all([supabase.from('hr_employees').select('id,employee_code,first_name,last_name,nickname,employment_status,hire_date,department:hr_departments!hr_employees_department_id_fkey(name),position:hr_positions!hr_employees_position_id_fkey(name)').in('employment_status',['active','probation']).order('hire_date',{ascending:false,nullsFirst:false}),supabase.from('plan_employee_profiles').select('*'),supabase.from('plan_employee_evaluations').select('*').order('evaluation_date',{ascending:false})]);const err=er.error||pr.error||vr.error;if(err)setError(err.message.includes('plan_employee_evaluations')?'กรุณารัน migration 351_plan_employee_evaluations.sql':err.message);const list=(er.data||[]) as unknown as Employee[];setEmployees(list);setProfiles(pr.data||[]);setEvaluations((vr.data||[]) as Evaluation[]);setSelectedId(id=>id||list[0]?.id||'');setLoading(false)},[])
 useEffect(()=>{void load()},[load])
 const cutoff=new Date();cutoff.setDate(cutoff.getDate()-180);const cutoffText=cutoff.toISOString().slice(0,10)
 const newEmployees=employees.filter(e=>{const p=profiles.find(x=>x.employee_id===e.id);return showAll||e.employment_status==='probation'||(e.hire_date&&e.hire_date>=cutoffText)||['pending','probation'].includes(p?.onboarding_status)})
 const filtered=newEmployees.filter(e=>`${e.employee_code} ${e.nickname||''} ${e.first_name} ${e.last_name} ${e.department?.name||''}`.toLowerCase().includes(search.toLowerCase()))
 const selected=employees.find(e=>e.id===selectedId),profile=profiles.find(p=>p.employee_id===selectedId),history=evaluations.filter(e=>e.employee_id===selectedId)
 const period=useMemo(()=>{if(periodType==='daily')return{start:date,end:date};const d=new Date(`${date}T00:00:00`),day=(d.getDay()+6)%7,start=new Date(d);start.setDate(d.getDate()-day);const end=new Date(start);end.setDate(start.getDate()+6);return{start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)}},[date,periodType])
 const average=(Object.values(scores).reduce((a,b)=>a+b,0)/5).toFixed(1)
 async function save(){if(!selectedId)return;setSaving(true);setError('');const {error:e}=await supabase.from('plan_employee_evaluations').upsert({employee_id:selectedId,period_type:periodType,evaluation_date:date,period_start:period.start,period_end:period.end,attendance_score:scores.attendance,learning_score:scores.learning,quality_score:scores.quality,teamwork_score:scores.teamwork,discipline_score:scores.discipline,result,strengths,improvements,note},{onConflict:'employee_id,period_type,period_start,period_end'});if(!e){const onboarding_status:OnboardingStatus=result==='passed'?'passed':result==='failed'?'failed':'probation';const {error:pe}=await supabase.from('plan_employee_profiles').upsert({employee_id:selectedId,responsibility_level:profile?.responsibility_level||'operator',is_available_for_planning:profile?.is_available_for_planning??true,onboarding_status,review_date:date,onboarding_note:note},{onConflict:'employee_id'});if(pe)setError(pe.message)}setSaving(false);if(e)setError(e.message);else{setMessage('บันทึกผลประเมินแล้ว');setStrengths('');setImprovements('');setNote('');await load()}}
 if(loading)return <div className="rounded-xl border bg-white p-12 text-center text-gray-500">กำลังโหลดข้อมูลประเมิน...</div>
 return <div className="grid gap-4 lg:grid-cols-[360px_minmax(0,1fr)]"><aside className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="space-y-3 border-b p-4"><input className="w-full rounded-lg border px-3 py-2" placeholder="ค้นหาพนักงานใหม่" value={search} onChange={e=>setSearch(e.target.value)}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/> แสดงพนักงานทั้งหมด</label><p className="text-xs text-gray-500">พนักงานใหม่หมายถึงรับเข้าภายใน 180 วัน หรือมีสถานะทดลองงาน · พบ {filtered.length} คน</p></div><div className="max-h-[680px] overflow-y-auto">{filtered.map(e=>{const p=profiles.find(x=>x.employee_id===e.id),count=evaluations.filter(v=>v.employee_id===e.id).length;return <button key={e.id} onClick={()=>setSelectedId(e.id)} className={`w-full border-b p-3 text-left hover:bg-blue-50 ${selectedId===e.id?'bg-blue-50':''}`}><div className="flex justify-between"><b>{e.employee_code} · {e.nickname||'-'}</b><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs">{count} ครั้ง</span></div><p className="mt-1 text-sm">{fullName(e)}</p><p className="text-xs text-gray-500">เริ่มงาน {e.hire_date||'-'} · {statusLabels[p?.onboarding_status as OnboardingStatus]||'รอประเมิน'}</p></button>})}</div></aside>
 <main className="min-w-0 space-y-4">{selected&&<><div className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-bold">{selected.employee_code} · {fullName(selected)} ({selected.nickname||'-'})</h3><p className="text-sm text-gray-500">{selected.position?.name||'-'} · {selected.department?.name||'-'} · เริ่มงาน {selected.hire_date||'-'}</p></div><span className="h-fit rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-700">{statusLabels[profile?.onboarding_status as OnboardingStatus]||'รอประเมิน'}</span></div></div>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message&&<p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}
 <div className="rounded-xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">บันทึกการประเมิน</h3><div className="mt-4 grid gap-3 md:grid-cols-3"><label><span className="mb-1 block text-sm">รอบประเมิน</span><select className="w-full rounded-lg border px-3 py-2" value={periodType} onChange={e=>setPeriodType(e.target.value as any)}><option value="daily">รายวัน</option><option value="weekly">รายสัปดาห์</option></select></label><label><span className="mb-1 block text-sm">วันที่ประเมิน</span><input type="date" className="w-full rounded-lg border px-3 py-2" value={date} onChange={e=>setDate(e.target.value)}/></label><div><span className="mb-1 block text-sm">ช่วงที่ประเมิน</span><div className="rounded-lg bg-gray-50 px-3 py-2">{period.start} ถึง {period.end}</div></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{([['attendance','การเข้า–ออกงาน'],['learning','การเรียนรู้งาน'],['quality','คุณภาพงาน'],['teamwork','การทำงานร่วมกัน'],['discipline','วินัย']] as const).map(([key,label])=><label key={key}><span className="mb-1 block text-sm">{label}</span><select className="w-full rounded-lg border px-3 py-2" value={scores[key]} onChange={e=>setScores(s=>({...s,[key]:Number(e.target.value)}))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} — {n===1?'ต้องปรับปรุงมาก':n===2?'ต้องปรับปรุง':n===3?'ผ่านมาตรฐาน':n===4?'ดี': 'ดีมาก'}</option>)}</select></label>)}</div><div className="mt-4 grid gap-3 md:grid-cols-3"><label><span className="mb-1 block text-sm">จุดเด่น</span><textarea className="w-full rounded-lg border p-3" rows={3} value={strengths} onChange={e=>setStrengths(e.target.value)}/></label><label><span className="mb-1 block text-sm">สิ่งที่ต้องพัฒนา</span><textarea className="w-full rounded-lg border p-3" rows={3} value={improvements} onChange={e=>setImprovements(e.target.value)}/></label><label><span className="mb-1 block text-sm">หมายเหตุ</span><textarea className="w-full rounded-lg border p-3" rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label></div><div className="mt-4 flex flex-wrap items-end justify-between gap-3 rounded-lg bg-gray-50 p-3"><div><p className="text-sm text-gray-500">คะแนนเฉลี่ย</p><p className="text-2xl font-bold">{average} / 5</p></div><label><span className="mb-1 block text-sm">สรุปผลรอบนี้</span><select className="rounded-lg border px-3 py-2" value={result} onChange={e=>setResult(e.target.value as any)}>{Object.entries(resultLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button className="rounded-lg bg-blue-600 px-5 py-2 font-semibold text-white disabled:opacity-50" disabled={!canEdit||saving} onClick={save}>{saving?'กำลังบันทึก...':'บันทึกการประเมิน'}</button></div></div>
 <div className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="border-b p-4"><h3 className="font-semibold">ประวัติการประเมิน</h3></div>{history.length===0?<p className="p-8 text-center text-gray-500">ยังไม่มีประวัติการประเมิน</p>:<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-3">รอบ</th><th>ช่วงวันที่</th><th>คะแนนเฉลี่ย</th><th>ผล</th><th>จุดเด่น</th><th>สิ่งที่ต้องพัฒนา</th></tr></thead><tbody>{history.map(v=>{const avg=((v.attendance_score+v.learning_score+v.quality_score+v.teamwork_score+v.discipline_score)/5).toFixed(1);return <tr key={v.id} className="border-t"><td className="p-3">{v.period_type==='daily'?'รายวัน':'รายสัปดาห์'}</td><td>{v.period_start} ถึง {v.period_end}</td><td className="font-semibold">{avg}</td><td>{resultLabels[v.result]}</td><td>{v.strengths||'-'}</td><td>{v.improvements||'-'}</td></tr>})}</tbody></table></div>}</div></>}</main></div>
}
