import { useCallback, useEffect, useState } from 'react'
import type { MachineryMachine } from '../lib/machineryApi'
import { changeMachineStatus } from '../lib/machineryApi'
import { buildReadiness, createIncident, disableChecklistItem, fetchChecklistItems, fetchIncidents, fetchInspectionAccessCandidates, fetchInspectionAccessUserIds, fetchTodayInspections, INCIDENT_STATUS_LABELS, saveChecklistItem, saveInspectionAccessUserIds, submitInspection, updateIncidentStatus, type ChecklistItem, type IncidentStatus, type InspectionResult, type MachineryIncident, type MachineryInspectionUser, type MachineReadiness } from '../lib/machineryOperationsApi'

const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const input='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm'
const dt=(v:string|null)=>v?new Date(v).toLocaleString('th-TH',{dateStyle:'short',timeStyle:'short'}):'-'

export function MachineryChecklist({machines,onChanged}:{machines:MachineryMachine[];onChanged?:()=>void}){
 const [items,setItems]=useState<ChecklistItem[]>([]),[readiness,setReadiness]=useState<MachineReadiness[]>([]),[machineId,setMachineId]=useState(machines[0]?.id||''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [values,setValues]=useState<Record<string,{passed:boolean;value_text?:string;value_number?:number;note?:string}>>({})
 const load=useCallback(async()=>{try{const [it,ins]=await Promise.all([fetchChecklistItems(),fetchTodayInspections(today())]);setItems(it);setReadiness(buildReadiness(machines.map(m=>m.id),it,ins.inspections,ins.results as InspectionResult[]));const savedInspection=ins.inspections.find(row=>row.machine_id===machineId);const savedValues:Record<string,{passed:boolean;value_text?:string;value_number?:number;note?:string}>={};if(savedInspection){(ins.results as InspectionResult[]).filter(row=>row.inspection_id===savedInspection.id&&row.passed!==null).forEach(row=>{savedValues[row.checklist_item_id]={passed:row.passed===true,...(row.value_text?{value_text:row.value_text}:{}),...(row.value_number!==null?{value_number:row.value_number}:{}),...(row.note?{note:row.note}:{})}})}setValues(savedValues)}catch(e){setError(e instanceof Error?e.message:String(e))}},[machines,machineId])
 useEffect(()=>{load()},[load]);useEffect(()=>{if(!machineId&&machines[0])setMachineId(machines[0].id)},[machines,machineId])
 const selected=items.filter(i=>i.machine_id===machineId)
 async function submit(){setBusy(true);setError('');try{await submitInspection(machineId,today(),values);await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <section className="space-y-4"><div className="rounded-xl border bg-white p-4"><h2 className="text-lg font-bold">ตรวจความพร้อมเครื่องจักร</h2><p className="text-sm text-gray-500">ต้องผ่านรายการบังคับทั้งหมด จึงจะแสดงว่าพร้อมใน Master Plan</p><select className={`${input} mt-3 max-w-md`} value={machineId} onChange={e=>{setMachineId(e.target.value);setValues({})}}>{machines.map(m=><option key={m.id} value={m.id}>{m.name}{m.department_name?` — ${m.department_name} L${(m.line_index??0)+1}`:''}</option>)}</select></div>
 {error&&<div className="rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{machines.map(m=>{const r=readiness.find(x=>x.machine_id===m.id);const isSelected=machineId===m.id;const cls=r?.status==='ready'?'bg-emerald-50 text-emerald-700':r?.status==='failed'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700';return <button key={m.id} type="button" aria-pressed={isSelected} onClick={()=>{setMachineId(m.id);setValues({})}} className={`rounded-xl border p-3 text-left transition-all ${cls} ${isSelected?'border-blue-600 ring-2 ring-blue-500 ring-offset-2 shadow-md':'border-gray-200 hover:border-gray-400 hover:shadow-sm'}`}><b>{m.name}</b><div className="text-xs mt-1">{r?.status==='ready'?'พร้อมใช้งาน':r?.status==='failed'?'ตรวจไม่ผ่าน':r?.status==='no_checklist'?'ยังไม่ได้ตั้ง Checklist':'ยังตรวจไม่ครบ'} · {r?.passed_count||0}/{r?.required_count||0}</div></button>})}</div>
 <div className="rounded-xl border bg-white p-4 space-y-3">{selected.length===0?<p className="text-gray-500">เครื่องนี้ยังไม่มี Checklist กรุณาตั้งค่าที่แท็บตั้งค่าเครื่อง</p>:selected.map(i=><div key={i.id} className="rounded-lg border p-3"><div className="flex justify-between gap-2"><b>{i.label}{i.is_required&&<span className="text-red-500"> *</span>}</b><div className="flex gap-2"><button onClick={()=>setValues(v=>({...v,[i.id]:{...v[i.id],passed:true}}))} className={`rounded px-3 py-1 text-sm ${values[i.id]?.passed===true?'bg-emerald-600 text-white':'bg-gray-100'}`}>ผ่าน</button><button onClick={()=>setValues(v=>({...v,[i.id]:{...v[i.id],passed:false}}))} className={`rounded px-3 py-1 text-sm ${values[i.id]?.passed===false?'bg-red-600 text-white':'bg-gray-100'}`}>ไม่ผ่าน</button></div></div>{i.description&&<p className="text-xs text-gray-500 mt-1">{i.description}</p>}{i.input_type!=='boolean'&&<input className={`${input} mt-2`} type={i.input_type==='number'?'number':'text'} placeholder={i.input_type==='number'?`${i.min_value??''}–${i.max_value??''} ${i.unit||''}`:'ค่าที่ตรวจพบ'} onChange={e=>setValues(v=>({...v,[i.id]:{...v[i.id],passed:v[i.id]?.passed??false,...(i.input_type==='number'?{value_number:Number(e.target.value)}:{value_text:e.target.value})}}))}/>}</div>)}
 {selected.length>0&&<button disabled={busy} onClick={submit} className="rounded-lg bg-emerald-600 px-4 py-2 font-semibold text-white disabled:opacity-50">{busy?'กำลังบันทึก…':'บันทึกผลตรวจวันนี้'}</button>}</div></section>
}

export function MachineryMaintenance({machines,onChanged}:{machines:MachineryMachine[];onChanged?:()=>void}){
 const [rows,setRows]=useState<MachineryIncident[]>([]),[machineId,setMachineId]=useState(machines[0]?.id||''),[title,setTitle]=useState(''),[useCustomTitle,setUseCustomTitle]=useState(false),[symptom,setSymptom]=useState(''),[severity,setSeverity]=useState<MachineryIncident['severity']>('medium'),[expected,setExpected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{try{setRows(await fetchIncidents())}catch(e){setError(e instanceof Error?e.message:String(e))}},[]);useEffect(()=>{load()},[load])
 const incidentTitles=machines.find(machine=>machine.id===machineId)?.incident_titles||[]
 async function create(){if(!machineId||!title.trim())return;setBusy(true);try{await createIncident({machine_id:machineId,title,symptom,severity,expected_ready_at:expected?new Date(expected).toISOString():null});await changeMachineStatus(machineId,'broken',title);setTitle('');setUseCustomTitle(false);setSymptom('');setExpected('');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function advance(r:MachineryIncident,status:IncidentStatus){setBusy(true);try{await updateIncidentStatus(r.id,status);if(status==='repairing')await changeMachineStatus(r.machine_id,'repairing',r.ticket_no);if(status==='ready'||status==='closed')await changeMachineStatus(r.machine_id,'power_off',`${r.ticket_no} ซ่อมเสร็จ รอตรวจ/เริ่มใช้งาน`);await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const next:Partial<Record<IncidentStatus,IncidentStatus>>={reported:'accepted',accepted:'repairing',repairing:'testing',testing:'ready',ready:'closed'}
 return <section className="space-y-4"><div className="rounded-xl border bg-white p-4"><h2 className="text-lg font-bold">แจ้งปัญหาเครื่องจักร / ใบแจ้งซ่อม</h2><div className="mt-3 grid gap-3 md:grid-cols-2 lg:grid-cols-5"><select className={input} value={machineId} onChange={e=>{setMachineId(e.target.value);setTitle('');setUseCustomTitle(false)}}>{machines.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><div>{incidentTitles.length>0&&<select className={input} value={useCustomTitle?'__custom__':title} onChange={e=>{if(e.target.value==='__custom__'){setTitle('');setUseCustomTitle(true)}else{setTitle(e.target.value);setUseCustomTitle(false)}}}><option value="">เลือกหัวข้อ/อาการหลัก *</option>{incidentTitles.map(option=><option key={option} value={option}>{option}</option>)}<option value="__custom__">อื่นๆ (ระบุเอง)</option></select>}{(incidentTitles.length===0||useCustomTitle)&&<input className={`${input} ${incidentTitles.length>0?'mt-2':''}`} value={title} onChange={e=>setTitle(e.target.value)} placeholder="หัวข้อ/อาการหลัก *"/>}</div><input className={input} value={symptom} onChange={e=>setSymptom(e.target.value)} placeholder="รายละเอียดอาการ"/><select className={input} value={severity} onChange={e=>setSeverity(e.target.value as MachineryIncident['severity'])}><option value="low">ต่ำ</option><option value="medium">ปานกลาง</option><option value="high">สูง</option><option value="critical">วิกฤต</option></select><input className={input} type="datetime-local" value={expected} onChange={e=>setExpected(e.target.value)} title="คาดว่าจะพร้อม"/></div><button disabled={busy||!title.trim()} onClick={create} className="mt-3 rounded-lg bg-red-600 px-4 py-2 font-semibold text-white disabled:opacity-50">เปิดใบแจ้งซ่อม</button></div>{error&&<div className="rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">ใบงาน</th><th className="p-3 text-left">เครื่อง/อาการ</th><th className="p-3">แจ้งเมื่อ</th><th className="p-3">คาดว่าพร้อม</th><th className="p-3">สถานะ</th><th className="p-3"></th></tr></thead><tbody>{rows.map(r=>{const n=next[r.status];return <tr key={r.id} className="border-t"><td className="p-3 font-mono">{r.ticket_no}</td><td className="p-3"><b>{machines.find(m=>m.id===r.machine_id)?.name||'-'}</b><div>{r.title}</div><div className="text-xs text-gray-500">{r.symptom}</div></td><td className="p-3 text-center">{dt(r.reported_at)}</td><td className="p-3 text-center">{dt(r.expected_ready_at)}</td><td className="p-3 text-center"><span className="rounded-full bg-amber-100 px-2 py-1">{INCIDENT_STATUS_LABELS[r.status]}</span></td><td className="p-3 text-right">{n&&<button disabled={busy} onClick={()=>advance(r,n)} className="rounded bg-blue-600 px-3 py-1.5 text-white">→ {INCIDENT_STATUS_LABELS[n]}</button>}</td></tr>})}{!rows.length&&<tr><td colSpan={6} className="p-8 text-center text-gray-500">ยังไม่มีใบแจ้งซ่อม</td></tr>}</tbody></table></div></section>
}

export function ChecklistSettings({machines}:{machines:MachineryMachine[]}) {
 const [machineId,setMachineId]=useState(machines[0]?.id||''),[items,setItems]=useState<ChecklistItem[]>([]),[label,setLabel]=useState(''),[description,setDescription]=useState(''),[required,setRequired]=useState(true),[error,setError]=useState(''),[busyId,setBusyId]=useState<string|null>(null)
 const [editingId,setEditingId]=useState<string|null>(null),[editLabel,setEditLabel]=useState(''),[editDescription,setEditDescription]=useState(''),[editRequired,setEditRequired]=useState(true)
 const [accessUsers,setAccessUsers]=useState<MachineryInspectionUser[]>([]),[accessUserIds,setAccessUserIds]=useState<Set<string>>(new Set()),[accessBusy,setAccessBusy]=useState(false),[accessLoaded,setAccessLoaded]=useState(false)
 const load=useCallback(async()=>{if(!machineId)return;try{setItems(await fetchChecklistItems(machineId));setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}},[machineId])
 useEffect(()=>{load()},[load])
 useEffect(()=>{if(!machineId)return;let active=true;setAccessLoaded(false);Promise.all([fetchInspectionAccessCandidates(),fetchInspectionAccessUserIds(machineId)]).then(([users,ids])=>{if(!active)return;setAccessUsers(users);setAccessUserIds(new Set(ids));setAccessLoaded(true)}).catch(e=>{if(active)setError(e instanceof Error?e.message:String(e))});return()=>{active=false}},[machineId])
 async function saveAccess(){if(!machineId)return;try{setAccessBusy(true);setError('');await saveInspectionAccessUserIds(machineId,[...accessUserIds])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setAccessBusy(false)}}
 async function add(){if(!label.trim())return;try{setBusyId('new');setError('');await saveChecklistItem({machine_id:machineId,label,description,is_required:required,input_type:'boolean',frequency:'daily',requires_photo:false,sort_order:items.length,is_active:true});setLabel('');setDescription('');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusyId(null)}}
 function beginEdit(item:ChecklistItem){setEditingId(item.id);setEditLabel(item.label);setEditDescription(item.description||'');setEditRequired(item.is_required);setError('')}
 async function saveEdit(item:ChecklistItem){if(!editLabel.trim())return;try{setBusyId(item.id);setError('');await saveChecklistItem({...item,label:editLabel,description:editDescription,is_required:editRequired});setEditingId(null);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusyId(null)}}
 async function remove(item:ChecklistItem){try{setBusyId(item.id);setError('');await disableChecklistItem(item.id);if(editingId===item.id)setEditingId(null);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusyId(null)}}
 return <div className="space-y-4">
 <div className="rounded-xl border bg-white p-4">
  <div className="flex flex-wrap items-start justify-between gap-3"><h3 className="font-bold">ผู้ใช้ที่เห็นเมนูตรวจความพร้อม</h3><button type="button" disabled={accessBusy||!accessLoaded} onClick={saveAccess} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{accessBusy?'กำลังบันทึก…':'บันทึกสิทธิ์ผู้ใช้'}</button></div>
  <select className={`${input} mt-3`} value={machineId} onChange={e=>{setMachineId(e.target.value);setEditingId(null)}}>{machines.map(machine=><option key={machine.id} value={machine.id}>{machine.name}</option>)}</select>
  <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{accessUsers.map(user=><label key={user.id} className={`flex min-w-0 cursor-pointer items-center gap-3 rounded-lg border p-3 ${accessUserIds.has(user.id)?'border-blue-300 bg-blue-50':'border-gray-200'}`}><input type="checkbox" checked={accessUserIds.has(user.id)} onChange={e=>setAccessUserIds(current=>{const next=new Set(current);if(e.target.checked)next.add(user.id);else next.delete(user.id);return next})}/><span className="min-w-0"><b className="block truncate text-sm">{user.username||user.email||user.id}</b><span className="block truncate text-xs text-gray-500">{user.role}</span></span></label>)}</div>
  {accessLoaded&&accessUsers.length===0&&<p className="mt-3 text-sm text-gray-400">ไม่มีผู้ใช้เพิ่มเติมในกลุ่ม Machinery</p>}
 </div>
 <div className="rounded-xl border bg-white p-4">
  <h3 className="font-bold">Checklist ก่อนใช้งาน</h3>
  <div className="mt-3 grid gap-2 md:grid-cols-[1fr_1fr_auto_auto]"><input className={input} value={label} onChange={e=>setLabel(e.target.value)} placeholder="รายการตรวจ *"/><input className={input} value={description} onChange={e=>setDescription(e.target.value)} placeholder="คำอธิบาย"/><label className="flex items-center gap-2"><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/> บังคับ</label><button disabled={busyId==='new'||!label.trim()} onClick={add} className="rounded-lg bg-emerald-600 px-4 py-2 text-white disabled:opacity-50">{busyId==='new'?'กำลังเพิ่ม…':'เพิ่ม'}</button></div>
  {error&&<p className="mt-2 text-red-600">{error}</p>}
  <div className="mt-3 space-y-2">{items.map((item,index)=>editingId===item.id
   ? <div key={item.id} className="rounded-lg border border-blue-300 bg-blue-50/40 p-3"><div className="grid gap-2 md:grid-cols-[1fr_1fr_auto]"><input autoFocus className={input} value={editLabel} onChange={e=>setEditLabel(e.target.value)} placeholder="รายการตรวจ *"/><input className={input} value={editDescription} onChange={e=>setEditDescription(e.target.value)} placeholder="คำอธิบาย"/><label className="flex items-center gap-2 whitespace-nowrap"><input type="checkbox" checked={editRequired} onChange={e=>setEditRequired(e.target.checked)}/> บังคับ</label></div><div className="mt-2 flex justify-end gap-2"><button disabled={busyId===item.id} onClick={()=>setEditingId(null)} className="rounded-lg border bg-white px-3 py-1.5 text-sm disabled:opacity-50">ยกเลิก</button><button disabled={busyId===item.id||!editLabel.trim()} onClick={()=>saveEdit(item)} className="rounded-lg bg-blue-600 px-3 py-1.5 text-sm text-white disabled:opacity-50">{busyId===item.id?'กำลังบันทึก…':'บันทึก'}</button></div></div>
   : <div key={item.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><div className="min-w-0"><div>{index+1}. {item.label} {item.is_required&&<b className="text-red-500">*</b>}</div>{item.description&&<div className="mt-1 text-sm text-gray-500">{item.description}</div>}</div><div className="flex shrink-0 gap-3"><button onClick={()=>beginEdit(item)} className="text-sm font-medium text-blue-600">แก้ไข</button><button disabled={busyId===item.id} onClick={()=>remove(item)} className="text-sm text-red-600 disabled:opacity-50">นำออก</button></div></div>)}</div>
 </div></div>
}
