import { useCallback, useEffect, useState } from 'react'
import type { MachineryMachine } from '../lib/machineryApi'
import { changeMachineStatus } from '../lib/machineryApi'
import { buildReadiness, createIncident, disableChecklistItem, fetchChecklistItems, fetchIncidents, fetchTodayInspections, INCIDENT_STATUS_LABELS, saveChecklistItem, submitInspection, updateIncidentStatus, type ChecklistItem, type IncidentStatus, type InspectionResult, type MachineryIncident, type MachineReadiness } from '../lib/machineryOperationsApi'

const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const input='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm'
const dt=(v:string|null)=>v?new Date(v).toLocaleString('th-TH',{dateStyle:'short',timeStyle:'short'}):'-'

export function MachineryChecklist({machines,onChanged}:{machines:MachineryMachine[];onChanged?:()=>void}){
 const [items,setItems]=useState<ChecklistItem[]>([]),[readiness,setReadiness]=useState<MachineReadiness[]>([]),[machineId,setMachineId]=useState(machines[0]?.id||''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [values,setValues]=useState<Record<string,{passed:boolean;value_text?:string;value_number?:number;note?:string}>>({})
 const load=useCallback(async()=>{try{const [it,ins]=await Promise.all([fetchChecklistItems(),fetchTodayInspections(today())]);setItems(it);setReadiness(buildReadiness(machines.map(m=>m.id),it,ins.inspections,ins.results as InspectionResult[]))}catch(e){setError(e instanceof Error?e.message:String(e))}},[machines])
 useEffect(()=>{load()},[load]);useEffect(()=>{if(!machineId&&machines[0])setMachineId(machines[0].id)},[machines,machineId])
 const selected=items.filter(i=>i.machine_id===machineId)
 async function submit(){setBusy(true);setError('');try{await submitInspection(machineId,today(),values);await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <section className="space-y-4"><div className="rounded-xl border bg-white p-4"><h2 className="text-lg font-bold">ตรวจความพร้อมเครื่องจักร</h2><p className="text-sm text-gray-500">ต้องผ่านรายการบังคับทั้งหมด จึงจะแสดงว่าพร้อมใน Master Plan</p><select className={`${input} mt-3 max-w-md`} value={machineId} onChange={e=>{setMachineId(e.target.value);setValues({})}}>{machines.map(m=><option key={m.id} value={m.id}>{m.name}{m.department_name?` — ${m.department_name} L${(m.line_index??0)+1}`:''}</option>)}</select></div>
 {error&&<div className="rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{machines.map(m=>{const r=readiness.find(x=>x.machine_id===m.id);const cls=r?.status==='ready'?'bg-emerald-50 text-emerald-700':r?.status==='failed'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700';return <button key={m.id} onClick={()=>setMachineId(m.id)} className={`rounded-xl border p-3 text-left ${cls}`}><b>{m.name}</b><div className="text-xs mt-1">{r?.status==='ready'?'พร้อมใช้งาน':r?.status==='failed'?'ตรวจไม่ผ่าน':r?.status==='no_checklist'?'ยังไม่ได้ตั้ง Checklist':'ยังตรวจไม่ครบ'} · {r?.passed_count||0}/{r?.required_count||0}</div></button>})}</div>
 <div className="rounded-xl border bg-white p-4 space-y-3">{selected.length===0?<p className="text-gray-500">เครื่องนี้ยังไม่มี Checklist กรุณาตั้งค่าที่แท็บตั้งค่าเครื่อง</p>:selected.map(i=><div key={i.id} className="rounded-lg border p-3"><div className="flex justify-between gap-2"><b>{i.label}{i.is_required&&<span className="text-red-500"> *</span>}</b><div className="flex gap-2"><button onClick={()=>setValues(v=>({...v,[i.id]:{...v[i.id],passed:true}}))} className={`rounded px-3 py-1 text-sm ${values[i.id]?.passed===true?'bg-emerald-600 text-white':'bg-gray-100'}`}>ผ่าน</button><button onClick={()=>setValues(v=>({...v,[i.id]:{...v[i.id],passed:false}}))} className={`rounded px-3 py-1 text-sm ${values[i.id]?.passed===false?'bg-red-600 text-white':'bg-gray-100'}`}>ไม่ผ่าน</button></div></div>{i.description&&<p className="text-xs text-gray-500 mt-1">{i.description}</p>}{i.input_type!=='boolean'&&<input className={`${input} mt-2`} type={i.input_type==='number'?'number':'text'} placeholder={i.input_type==='number'?`${i.min_value??''}–${i.max_value??''} ${i.unit||''}`:'ค่าที่ตรวจพบ'} onChange={e=>setValues(v=>({...v,[i.id]:{...v[i.id],passed:v[i.id]?.passed??false,...(i.input_type==='number'?{value_number:Number(e.target.value)}:{value_text:e.target.value})}}))}/>}</div>)}
 {selected.length>0&&<button disabled={busy} onClick={submit} className="rounded-lg bg-emerald-600 px-4 py-2 font-semibold text-white disabled:opacity-50">{busy?'กำลังบันทึก…':'บันทึกผลตรวจวันนี้'}</button>}</div></section>
}

export function MachineryMaintenance({machines,onChanged}:{machines:MachineryMachine[];onChanged?:()=>void}){
 const [rows,setRows]=useState<MachineryIncident[]>([]),[machineId,setMachineId]=useState(machines[0]?.id||''),[title,setTitle]=useState(''),[symptom,setSymptom]=useState(''),[severity,setSeverity]=useState<MachineryIncident['severity']>('medium'),[expected,setExpected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{try{setRows(await fetchIncidents())}catch(e){setError(e instanceof Error?e.message:String(e))}},[]);useEffect(()=>{load()},[load])
 async function create(){if(!machineId||!title.trim())return;setBusy(true);try{await createIncident({machine_id:machineId,title,symptom,severity,expected_ready_at:expected?new Date(expected).toISOString():null});await changeMachineStatus(machineId,'broken',title);setTitle('');setSymptom('');setExpected('');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function advance(r:MachineryIncident,status:IncidentStatus){setBusy(true);try{await updateIncidentStatus(r.id,status);if(status==='repairing')await changeMachineStatus(r.machine_id,'repairing',r.ticket_no);if(status==='ready'||status==='closed')await changeMachineStatus(r.machine_id,'power_off',`${r.ticket_no} ซ่อมเสร็จ รอตรวจ/เริ่มใช้งาน`);await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const next:Partial<Record<IncidentStatus,IncidentStatus>>={reported:'accepted',accepted:'repairing',repairing:'testing',testing:'ready',ready:'closed'}
 return <section className="space-y-4"><div className="rounded-xl border bg-white p-4"><h2 className="text-lg font-bold">แจ้งปัญหาเครื่องจักร / ใบแจ้งซ่อม</h2><div className="mt-3 grid gap-3 md:grid-cols-2 lg:grid-cols-5"><select className={input} value={machineId} onChange={e=>setMachineId(e.target.value)}>{machines.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><input className={input} value={title} onChange={e=>setTitle(e.target.value)} placeholder="หัวข้อ/อาการหลัก *"/><input className={input} value={symptom} onChange={e=>setSymptom(e.target.value)} placeholder="รายละเอียดอาการ"/><select className={input} value={severity} onChange={e=>setSeverity(e.target.value as MachineryIncident['severity'])}><option value="low">ต่ำ</option><option value="medium">ปานกลาง</option><option value="high">สูง</option><option value="critical">วิกฤต</option></select><input className={input} type="datetime-local" value={expected} onChange={e=>setExpected(e.target.value)} title="คาดว่าจะพร้อม"/></div><button disabled={busy||!title.trim()} onClick={create} className="mt-3 rounded-lg bg-red-600 px-4 py-2 font-semibold text-white disabled:opacity-50">เปิดใบแจ้งซ่อม</button></div>{error&&<div className="rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">ใบงาน</th><th className="p-3 text-left">เครื่อง/อาการ</th><th className="p-3">แจ้งเมื่อ</th><th className="p-3">คาดว่าพร้อม</th><th className="p-3">สถานะ</th><th className="p-3"></th></tr></thead><tbody>{rows.map(r=>{const n=next[r.status];return <tr key={r.id} className="border-t"><td className="p-3 font-mono">{r.ticket_no}</td><td className="p-3"><b>{machines.find(m=>m.id===r.machine_id)?.name||'-'}</b><div>{r.title}</div><div className="text-xs text-gray-500">{r.symptom}</div></td><td className="p-3 text-center">{dt(r.reported_at)}</td><td className="p-3 text-center">{dt(r.expected_ready_at)}</td><td className="p-3 text-center"><span className="rounded-full bg-amber-100 px-2 py-1">{INCIDENT_STATUS_LABELS[r.status]}</span></td><td className="p-3 text-right">{n&&<button disabled={busy} onClick={()=>advance(r,n)} className="rounded bg-blue-600 px-3 py-1.5 text-white">→ {INCIDENT_STATUS_LABELS[n]}</button>}</td></tr>})}{!rows.length&&<tr><td colSpan={6} className="p-8 text-center text-gray-500">ยังไม่มีใบแจ้งซ่อม</td></tr>}</tbody></table></div></section>
}

export function ChecklistSettings({machines}:{machines:MachineryMachine[]}){const[machineId,setMachineId]=useState(machines[0]?.id||''),[items,setItems]=useState<ChecklistItem[]>([]),[label,setLabel]=useState(''),[description,setDescription]=useState(''),[required,setRequired]=useState(true),[error,setError]=useState('');const load=useCallback(async()=>{try{setItems(await fetchChecklistItems(machineId))}catch(e){setError(e instanceof Error?e.message:String(e))}},[machineId]);useEffect(()=>{if(!machineId)return;fetchChecklistItems(machineId).then(setItems).catch(e=>setError(e instanceof Error?e.message:String(e)))},[machineId]);async function add(){if(!label.trim())return;try{await saveChecklistItem({machine_id:machineId,label,description,is_required:required,input_type:'boolean',frequency:'daily',requires_photo:false,sort_order:items.length,is_active:true});setLabel('');setDescription('');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}return <div className="rounded-xl border bg-white p-4"><h3 className="font-bold">Checklist ก่อนใช้งาน</h3><select className={`${input} mt-3`} value={machineId} onChange={e=>setMachineId(e.target.value)}>{machines.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><div className="mt-3 grid gap-2 md:grid-cols-[1fr_1fr_auto_auto]"><input className={input} value={label} onChange={e=>setLabel(e.target.value)} placeholder="รายการตรวจ *"/><input className={input} value={description} onChange={e=>setDescription(e.target.value)} placeholder="คำอธิบาย"/><label className="flex items-center gap-2"><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/> บังคับ</label><button onClick={add} className="rounded-lg bg-emerald-600 px-4 py-2 text-white">เพิ่ม</button></div>{error&&<p className="mt-2 text-red-600">{error}</p>}<div className="mt-3 space-y-2">{items.map((i,index)=><div key={i.id} className="flex items-center justify-between rounded-lg border p-2"><span>{index+1}. {i.label} {i.is_required&&<b className="text-red-500">*</b>}</span><button onClick={async()=>{await disableChecklistItem(i.id);load()}} className="text-sm text-red-600">นำออก</button></div>)}</div></div>}
