import { useCallback, useEffect, useMemo, useState } from 'react'
import { FiEye, FiPlus, FiSearch } from 'react-icons/fi'
import { useAuthContext } from '../../contexts/AuthContext'
import {
  deleteWarning, fetchEmployees, fetchWarningAuthorizedEmployees, fetchWarningOffenseTypes, fetchWarningPolicies, fetchWarnings,
  HR_WARNING_CERT_BUCKET, recommendWarningLevel, recordWarningAcknowledgement, saveWarningDecision, saveWarningPolicyLinks,
  transitionWarning, upsertWarning,
} from '../../lib/hrApi'
import type { HREmployee, HRWarning, HRWarningDecision, HRWarningOffenseType, HRWarningPolicy } from '../../types'
import Modal from '../ui/Modal'
import { useWmsModal } from '../wms/useWmsModal'
import HRDocumentAttachments from './HRDocumentAttachments'
import { AttachmentStrip } from './employee/AttachmentViewer'

const LEVELS: Record<string,{label:string;cls:string}> = {
  verbal:{label:'ตักเตือนด้วยวาจา',cls:'bg-yellow-50 text-yellow-800 border-yellow-200'},
  verbal_2:{label:'ตักเตือนด้วยวาจา ครั้งที่ 2 (เดิม)',cls:'bg-amber-50 text-amber-800 border-amber-200'},
  written_1:{label:'หนังสือเตือน ครั้งที่ 1',cls:'bg-orange-50 text-orange-800 border-orange-200'},
  written_2:{label:'หนังสือเตือน ครั้งที่ 2 (เดิม)',cls:'bg-red-50 text-red-700 border-red-200'},
  final:{label:'หนังสือเตือนครั้งสุดท้าย',cls:'bg-red-100 text-red-900 border-red-300'},
  termination_review:{label:'พิจารณาเลิกจ้าง',cls:'bg-slate-900 text-white border-slate-900'},
}
const SELECTABLE_LEVELS: HRWarning['warning_level'][] = ['verbal','written_1','final','termination_review']
const STATUSES: Record<string,{label:string;cls:string}> = {
  draft:{label:'แบบร่าง',cls:'bg-gray-100 text-gray-700'}, pending_review:{label:'รอตรวจสอบ',cls:'bg-sky-100 text-sky-800'},
  changes_requested:{label:'ส่งกลับแก้ไข',cls:'bg-amber-100 text-amber-800'}, pending_approval:{label:'รออนุมัติ',cls:'bg-violet-100 text-violet-800'},
  approved:{label:'อนุมัติแล้ว',cls:'bg-blue-100 text-blue-800'}, pending_acknowledgement:{label:'รอพนักงานรับทราบ',cls:'bg-orange-100 text-orange-800'},
  acknowledged:{label:'รับทราบแล้ว',cls:'bg-emerald-100 text-emerald-800'}, acknowledgement_refused:{label:'ปฏิเสธรับทราบ',cls:'bg-red-100 text-red-800'},
  termination_review:{label:'พิจารณาเลิกจ้าง',cls:'bg-slate-900 text-white'}, closed:{label:'ปิดเคส',cls:'bg-gray-200 text-gray-700'},
  cancelled:{label:'ยกเลิก',cls:'bg-gray-100 text-gray-500'}, issued:{label:'ออกใบเตือน (เดิม)',cls:'bg-blue-100 text-blue-800'},
  appealed:{label:'อุทธรณ์ (เดิม)',cls:'bg-indigo-100 text-indigo-800'}, resolved:{label:'ยุติ (เดิม)',cls:'bg-gray-200 text-gray-700'},
}
const APPROVAL_ACTIONS:Record<string,string>={submitted:'ส่งตรวจสอบ',approved:'อนุมัติ',returned:'ส่งกลับแก้ไข',cancelled:'ยกเลิก'}
const AUDIT_ACTIONS:Record<string,string>={insert:'สร้างรายการ',update:'แก้ไขข้อมูล',delete:'ลบรายการ'}
const ROLE_ACCESS = ['superadmin','admin','account','hr']
const empName=(e?:HREmployee|null)=>e?`${e.first_name} ${e.last_name}${e.nickname?` (${e.nickname})`:''}`:'-'
const dateText=(d?:string|null)=>d?new Date(d.length===10?`${d}T00:00:00`:d).toLocaleString('th-TH',{dateStyle:'medium',...(d.length===10?{}:{timeStyle:'short'})}):'-'
const emptyForm=():Partial<HRWarning>=>({employee_id:'',offense_type_id:'',warning_level:'verbal',recommended_level:'verbal',subject:'',description:'',corrective_action:'',incident_date:new Date().toISOString().slice(0,10),issued_date:new Date().toISOString().slice(0,10),status:'draft',attachment_urls:[],recommendation_basis:[]})

export default function WarningLetters(){
  const {user}=useAuthContext(); const canManage=ROLE_ACCESS.includes(user?.role??'')
  const [warnings,setWarnings]=useState<HRWarning[]>([]),[employees,setEmployees]=useState<HREmployee[]>([])
  const [offenses,setOffenses]=useState<HRWarningOffenseType[]>([]),[policies,setPolicies]=useState<HRWarningPolicy[]>([])
  const [authorizedEmployees,setAuthorizedEmployees]=useState<HREmployee[]>([])
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[filterStatus,setFilterStatus]=useState(''),[filterOffense,setFilterOffense]=useState('')
  const [formOpen,setFormOpen]=useState(false),[form,setForm]=useState<Partial<HRWarning>>(emptyForm()),[policyIds,setPolicyIds]=useState<string[]>([]),[saving,setSaving]=useState(false)
  const [view,setView]=useState<HRWarning|null>(null),[decisionTarget,setDecisionTarget]=useState<HRWarning|null>(null)
  const [ackTarget,setAckTarget]=useState<HRWarning|null>(null),[ackForm,setAckForm]=useState({outcome:'acknowledged' as 'acknowledged'|'refused',method:'in_person',note:'',witness_id:''})
  const [actionTarget,setActionTarget]=useState<{warning:HRWarning;action:'return'|'cancel'|'close'}|null>(null),[actionNote,setActionNote]=useState('')
  const [decision,setDecision]=useState<{outcome:HRWarningDecision['outcome'];reason:string;conditions:string;effective_date:string}>({outcome:'continued_employment',reason:'',conditions:'',effective_date:new Date().toISOString().slice(0,10)})
  const {showConfirm,showMessage,ConfirmModal,MessageModal}=useWmsModal({showCancelButton:false})
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [w,e,o,p,a]=await Promise.all([fetchWarnings(),fetchEmployees(),fetchWarningOffenseTypes(),fetchWarningPolicies(),fetchWarningAuthorizedEmployees()]);setWarnings(w);setEmployees(e);setOffenses(o);setPolicies(p);setAuthorizedEmployees(a)}catch(e){setError(e instanceof Error?e.message:'โหลดข้อมูลไม่สำเร็จ')}finally{setLoading(false)}},[])
  useEffect(()=>{load()},[load])
  const related=useMemo(()=>warnings.filter(w=>w.employee_id===form.employee_id&&(!form.offense_type_id||w.offense_type_id===form.offense_type_id)&&w.id!==form.id&& !['draft','cancelled'].includes(w.status)),[warnings,form.employee_id,form.offense_type_id,form.id])
  const filtered=useMemo(()=>warnings.filter(w=>(!filterStatus||w.status===filterStatus)&&(!filterOffense||w.offense_type_id===filterOffense)&&(!search.trim()||`${w.case_number??''} ${w.warning_number??''} ${w.subject} ${empName(w.employee)}`.toLowerCase().includes(search.trim().toLowerCase()))),[warnings,filterStatus,filterOffense,search])
  const refreshRecommendation=async(employeeId:string,offenseId:string)=>{if(!employeeId||!offenseId)return;try{const r=await recommendWarningLevel(employeeId,offenseId);setForm(f=>({...f,recommended_level:r.recommendedLevel,warning_level:r.recommendedLevel,recommendation_basis:r.basis,level_override_reason:''}))}catch(e){setError(e instanceof Error?e.message:'คำนวณระดับแนะนำไม่สำเร็จ')}}
  const openCreate=()=>{setForm(emptyForm());setPolicyIds([]);setFormOpen(true)}
  const openEdit=(w:HRWarning)=>{setForm({...w});setPolicyIds(w.policy_links?.map(x=>x.policy_id)??[]);setFormOpen(true)}
  const validate=(submit:boolean)=>{if(!form.employee_id)return'กรุณาเลือกพนักงาน';if(!form.subject?.trim())return'กรุณาระบุเรื่อง';if(!submit)return'';if(!form.offense_type_id)return'กรุณาเลือกประเภทความผิด';if(!form.incident_date)return'กรุณาระบุวันที่เกิดเหตุ';if(!form.corrective_action?.trim())return'กรุณาระบุสิ่งที่ต้องปรับปรุง / คำสั่งให้แก้ไข';if(!form.approver_id)return'กรุณาเลือกผู้อนุมัติ';if(form.warning_level!==form.recommended_level&&!form.level_override_reason?.trim())return'กรุณาระบุเหตุผลในการเปลี่ยนระดับการเตือน';return''}
  const save=async(submit=false)=>{const problem=validate(submit);if(problem){showMessage({message:problem});return}setSaving(true);try{const saved=await upsertWarning({...form,offense_type_id:form.offense_type_id||null,approver_id:form.approver_id||null,status:form.status??'draft',created_by_user:form.created_by_user??user?.id});await saveWarningPolicyLinks(saved.id,policyIds);if(submit)await transitionWarning(saved.id,'submit_review');setFormOpen(false);await load();showMessage({message:submit?'ส่งตรวจสอบแล้ว':'บันทึกร่างแล้ว'})}catch(e){showMessage({message:e instanceof Error?e.message:'บันทึกไม่สำเร็จ'})}finally{setSaving(false)}}
  const act=async(w:HRWarning,action:'send_approval'|'return'|'approve'|'cancel'|'close',note?:string)=>{if(['return','cancel','close'].includes(action)&&note===undefined){setActionNote('');setActionTarget({warning:w,action:action as 'return'|'cancel'|'close'});return}try{await transitionWarning(w.id,action,note||undefined);setView(null);setActionTarget(null);await load()}catch(e){showMessage({message:e instanceof Error?e.message:'ดำเนินการไม่สำเร็จ'})}}
  const confirmAction=async()=>{if(!actionTarget)return;if(actionTarget.action!=='close'&&!actionNote.trim()){showMessage({message:actionTarget.action==='return'?'กรุณาระบุเหตุผลที่ส่งกลับแก้ไข':'กรุณาระบุเหตุผลที่ยกเลิกเคส'});return}await act(actionTarget.warning,actionTarget.action,actionTarget.action==='close'?'confirmed':actionNote.trim())}
  const saveDecision=async()=>{if(!decisionTarget)return;if(!decision.reason.trim()){showMessage({message:'กรุณาระบุเหตุผลผลการพิจารณา'});return}try{await saveWarningDecision({warning_id:decisionTarget.id,...decision,approved_by:decisionTarget.approver_id});setDecisionTarget(null);await transitionWarning(decisionTarget.id,'close');await load()}catch(e){showMessage({message:e instanceof Error?e.message:'บันทึกผลไม่สำเร็จ'})}}
  const saveAcknowledgement=async()=>{if(!ackTarget)return;if(ackForm.outcome==='refused'&&!ackForm.witness_id){showMessage({message:'กรุณาระบุพยานเมื่อพนักงานปฏิเสธรับทราบ'});return}try{await recordWarningAcknowledgement(ackTarget.id,ackForm.outcome,ackForm.method,ackForm.note||undefined,ackForm.witness_id||undefined);setAckTarget(null);setView(null);await load()}catch(e){showMessage({message:e instanceof Error?e.message:'บันทึกการรับทราบไม่สำเร็จ'})}}
  if(loading)return <div className="py-20 text-center">กำลังโหลด...</div>
  return <div className="mt-4 space-y-5">
    {error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{[
      ['ทั้งหมด',warnings.length],['รอตรวจ',warnings.filter(w=>w.status==='pending_review').length],['รออนุมัติ',warnings.filter(w=>w.status==='pending_approval').length],['รอรับทราบ',warnings.filter(w=>w.status==='pending_acknowledgement').length],['ปฏิเสธรับทราบ',warnings.filter(w=>w.status==='acknowledgement_refused').length],['พิจารณาเลิกจ้าง',warnings.filter(w=>w.status==='termination_review').length],
    ].map(([label,count])=><div key={label} className="rounded-xl border bg-white p-4"><div className="text-2xl font-bold">{count}</div><div className="text-xs text-gray-500">{label}</div></div>)}</div>
    <div className="flex flex-wrap gap-3"><label className="relative min-w-56 flex-1"><FiSearch className="absolute left-3 top-3 text-gray-400"/><input className="w-full rounded-xl border py-2.5 pl-9 pr-3" value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาเลขเคส เลขใบเตือน พนักงาน หรือเรื่อง..."/></label><select className="rounded-xl border px-3" value={filterOffense} onChange={e=>setFilterOffense(e.target.value)}><option value="">ประเภทความผิดทั้งหมด</option>{offenses.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><select className="rounded-xl border px-3" value={filterStatus} onChange={e=>setFilterStatus(e.target.value)}><option value="">สถานะทั้งหมด</option>{Object.entries(STATUSES).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select>{canManage&&<button onClick={openCreate} className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2 text-white"><FiPlus/>สร้างเคสใบเตือน</button>}</div>
    <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-gray-50"><tr>{['เลขเคส / เลขใบเตือน','พนักงาน','ประเภทความผิด','ระดับ','เรื่อง','วันที่เกิดเหตุ','สถานะ','จัดการ'].map(x=><th key={x} className="whitespace-nowrap p-3 text-left">{x}</th>)}</tr></thead><tbody>{filtered.map(w=><tr key={w.id} className="border-t"><td className="p-3 text-xs"><div className="font-mono">{w.case_number??'-'}</div><div className="font-mono text-blue-600">{w.warning_number??'ยังไม่ออกเลข'}</div></td><td className="p-3">{empName(w.employee)}</td><td className="p-3">{w.offense_type?.name??'-'}</td><td className="p-3"><span className={`rounded-full border px-2 py-1 text-xs ${LEVELS[w.warning_level]?.cls}`}>{LEVELS[w.warning_level]?.label??w.warning_level}</span></td><td className="max-w-56 p-3"><div className="truncate">{w.subject}</div></td><td className="p-3">{dateText(w.incident_date)}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs ${STATUSES[w.status]?.cls}`}>{STATUSES[w.status]?.label??w.status}</span></td><td className="p-3"><div className="flex gap-2"><button onClick={()=>setView(w)} title="ดูรายละเอียด"><FiEye/></button>{canManage&&['draft','changes_requested'].includes(w.status)&&<button onClick={()=>openEdit(w)} className="text-blue-600">แก้ไข</button>}{canManage&&w.status==='draft'&&<button onClick={async()=>{if(await showConfirm({message:'ลบแบบร่างนี้หรือไม่?'})){await deleteWarning(w.id);await load()}}} className="text-red-600">ลบ</button>}</div></td></tr>)}{!filtered.length&&<tr><td colSpan={8} className="p-12 text-center text-gray-400">ไม่พบรายการ</td></tr>}</tbody></table></div>
    <Modal open={formOpen} onClose={()=>setFormOpen(false)} contentClassName="max-w-4xl"><div className="space-y-5 p-6"><h2 className="text-xl font-bold">{form.id?'แก้ไขเคสใบเตือน':'สร้างเคสใบเตือนใหม่'}</h2>
      <div className="grid gap-4 md:grid-cols-2"><Field label="พนักงาน *"><select className="input" value={form.employee_id??''} onChange={e=>{const employee_id=e.target.value;setForm(f=>({...f,employee_id}));void refreshRecommendation(employee_id,form.offense_type_id??'')}}><option value="">เลือกพนักงาน</option>{employees.filter(e=>e.employment_status==='active').map(e=><option key={e.id} value={e.id}>{e.employee_code} - {empName(e)}</option>)}</select></Field><Field label="ประเภทความผิด *"><select className="input" value={form.offense_type_id??''} onChange={e=>{const offense_type_id=e.target.value;setForm(f=>({...f,offense_type_id}));void refreshRecommendation(form.employee_id??'',offense_type_id)}}><option value="">เลือกประเภทความผิด</option>{offenses.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field></div>
      {form.employee_id&&form.offense_type_id&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><div className="font-semibold text-blue-900">ประวัติที่เกี่ยวข้อง ({related.length})</div>{related.length?<div className="mt-2 grid gap-2">{related.slice(0,8).map(w=><button key={w.id} onClick={()=>setView(w)} className="text-left text-sm text-blue-800 hover:underline">{dateText(w.incident_date)} — {LEVELS[w.warning_level]?.label} — {w.subject}</button>)}</div>:<p className="mt-1 text-sm text-blue-700">ไม่พบประวัติที่ยังมีผล</p>}</div>}
      <div className="grid gap-4 md:grid-cols-2"><Field label="ระดับการเตือน *"><select className="input" value={form.warning_level} onChange={e=>setForm(f=>({...f,warning_level:e.target.value as HRWarning['warning_level']}))}>{SELECTABLE_LEVELS.map(k=><option key={k} value={k}>{LEVELS[k].label}</option>)}</select><p className="mt-1 text-xs text-emerald-700">ระบบแนะนำ: {LEVELS[form.recommended_level??'verbal']?.label}</p></Field><Field label="ผู้อนุมัติ *"><select className="input" value={form.approver_id??''} onChange={e=>setForm(f=>({...f,approver_id:e.target.value||null}))}><option value="">เลือกผู้อนุมัติ</option>{authorizedEmployees.map(e=><option key={e.id} value={e.id}>{empName(e)}</option>)}</select></Field></div>
      {form.warning_level!==form.recommended_level&&<Field label="เหตุผลในการเปลี่ยนระดับการเตือน *"><textarea className="input" rows={2} value={form.level_override_reason??''} onChange={e=>setForm(f=>({...f,level_override_reason:e.target.value}))}/></Field>}
      <Field label="เรื่อง *"><input className="input" value={form.subject??''} onChange={e=>setForm(f=>({...f,subject:e.target.value}))}/></Field><Field label="รายละเอียดเหตุการณ์"><textarea className="input" rows={4} value={form.description??''} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/></Field>
      <div className="grid gap-4 md:grid-cols-2"><Field label="วันที่เกิดเหตุ *"><input type="date" className="input" value={form.incident_date??''} onChange={e=>setForm(f=>({...f,incident_date:e.target.value}))}/></Field><Field label="วันที่ออกใบเตือน"><input type="date" className="input" value={form.issued_date??''} onChange={e=>setForm(f=>({...f,issued_date:e.target.value}))}/></Field><Field label="ผู้ออกใบเตือน"><select className="input" value={form.issued_by??''} onChange={e=>setForm(f=>({...f,issued_by:e.target.value||undefined}))}><option value="">เลือก</option>{authorizedEmployees.map(e=><option key={e.id} value={e.id}>{empName(e)}</option>)}</select></Field><Field label="พยาน (ไม่บังคับ)"><select className="input" value={form.witness_id??''} onChange={e=>setForm(f=>({...f,witness_id:e.target.value||undefined}))}><option value="">ไม่มี</option>{employees.map(e=><option key={e.id} value={e.id}>{empName(e)}</option>)}</select></Field></div>
      <Field label="ระเบียบ / ข้อบังคับที่เกี่ยวข้อง"><div className="grid gap-2 sm:grid-cols-2">{policies.length?policies.map(p=><label key={p.id} className="flex gap-2 rounded-lg border p-2"><input type="checkbox" checked={policyIds.includes(p.id)} onChange={e=>setPolicyIds(e.target.checked?[...policyIds,p.id]:policyIds.filter(id=>id!==p.id))}/><span>{p.code?`${p.code} — `:''}{p.title}</span></label>):<p className="text-sm text-gray-400">ยังไม่มีระเบียบในฐานข้อมูล สามารถเพิ่มภายหลังและเชื่อมกับเอกสารบริษัทได้</p>}</div></Field>
      <Field label="สิ่งที่ต้องปรับปรุง / คำสั่งให้แก้ไข *"><textarea className="input" rows={4} value={form.corrective_action??''} onChange={e=>setForm(f=>({...f,corrective_action:e.target.value}))}/></Field>
      <HRDocumentAttachments employeeId={form.employee_id} category="warnings" paths={form.attachment_urls??[]} onChange={paths=>setForm(f=>({...f,attachment_urls:paths}))} onError={message=>showMessage({message})}/>
      <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">คำชี้แจงของพนักงานจะเพิ่มภายหลังในขั้นตอนรับทราบ ไม่ต้องกรอกตอนสร้างเคส</p><div className="flex justify-end gap-3"><button disabled={saving} onClick={()=>save(false)} className="rounded-xl border border-emerald-600 px-4 py-2 text-emerald-700">บันทึกร่าง</button><button disabled={saving} onClick={()=>save(true)} className="rounded-xl bg-emerald-600 px-5 py-2 text-white">ส่งตรวจสอบ</button></div>
    </div></Modal>
    <Modal open={!!view} onClose={()=>setView(null)} contentClassName="max-w-4xl">{view&&<div className="space-y-5 p-6"><div className="flex flex-wrap items-start justify-between gap-3 pr-12"><div className="min-w-0 flex-1"><h2 className="text-xl font-bold">{view.subject}</h2><p className="text-sm text-gray-500">{view.case_number} · {view.warning_number??'ยังไม่ออกเลขใบเตือน'}</p></div><span className={`shrink-0 rounded-full px-3 py-1 text-sm ${STATUSES[view.status]?.cls}`}>{STATUSES[view.status]?.label}</span></div><div className="grid gap-3 sm:grid-cols-3"><Info label="พนักงาน" value={empName(view.employee)}/><Info label="ประเภทความผิด" value={view.offense_type?.name??'-'}/><Info label="ระดับ" value={LEVELS[view.warning_level]?.label??view.warning_level}/><Info label="วันที่เกิดเหตุ" value={dateText(view.incident_date)}/><Info label="ผู้ออก" value={empName(view.issuer)}/><Info label="ผู้อนุมัติ" value={empName(view.approver)}/></div><Section title="รายละเอียด" text={view.description}/><Section title="สิ่งที่ต้องปรับปรุง / คำสั่งให้แก้ไข" text={view.corrective_action}/>{view.policy_links?.length?<div><h3 className="font-semibold">ระเบียบที่เกี่ยวข้อง</h3><ul className="mt-2 list-disc pl-5 text-sm">{view.policy_links.map(x=><li key={x.policy_id}>{x.policy?.title}</li>)}</ul></div>:null}{view.attachment_urls?.length?<AttachmentStrip label="หลักฐาน" items={view.attachment_urls.map(path=>({bucket:HR_WARNING_CERT_BUCKET,path}))}/>:null}
      {!!view.approvals?.length&&<Timeline title="ประวัติการตรวจ/อนุมัติ" rows={view.approvals.map(x=>`${dateText(x.acted_at)} — ${empName(x.actor)} — ${x.step==='review'?'ตรวจสอบ':'อนุมัติ'}: ${APPROVAL_ACTIONS[x.action]??x.action}${x.note?` — ${x.note}`:''}`)}/>}
      {!!view.responses?.length&&<Timeline title="คำชี้แจงของพนักงาน" rows={view.responses.map(x=>`${dateText(x.created_at)} — ${x.response_text}`)}/>}
      {!!view.acknowledgements?.length&&<Timeline title="การรับทราบ" rows={view.acknowledgements.map(x=>`${dateText(x.acknowledged_at)} — ${x.outcome==='acknowledged'?'รับทราบ':'ปฏิเสธรับทราบ'} (${x.method})${x.witness?` — พยาน ${empName(x.witness)}`:''}`)}/>}
      {!!view.decisions?.length&&<Timeline title="ผลพิจารณา" rows={view.decisions.map(x=>`${dateText(x.created_at)} — ${x.outcome}: ${x.reason??'-'}`)}/>}
      {!!view.audit_logs?.length&&<Timeline
        title="ประวัติการเปลี่ยนแปลง"
        rows={view.audit_logs.slice().sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(x=>{const oldLevel=x.old_data?.warning_level as string|undefined,newLevel=x.new_data?.warning_level as string|undefined;return `${dateText(x.created_at)} — ${empName(x.actor)} — ${AUDIT_ACTIONS[x.action]??x.action}${oldLevel&&newLevel&&oldLevel!==newLevel?` ระดับ ${LEVELS[oldLevel]?.label??oldLevel} → ${LEVELS[newLevel]?.label??newLevel}`:''}${x.reason?` — ${x.reason}`:''}`})}
      />}
      {canManage&&<div className="flex flex-wrap justify-end gap-2 border-t pt-4">{view.status==='pending_review'&&<><button onClick={()=>act(view,'return')} className="rounded-xl border px-4 py-2">ส่งกลับแก้ไข</button><button onClick={()=>act(view,'send_approval')} className="rounded-xl bg-blue-600 px-4 py-2 text-white">ส่งอนุมัติ</button></>}{view.status==='pending_approval'&&<><button onClick={()=>act(view,'return')} className="rounded-xl border px-4 py-2">ส่งกลับแก้ไข</button><button onClick={()=>act(view,'approve')} className="rounded-xl bg-emerald-600 px-4 py-2 text-white">อนุมัติและออกเลข</button></>}{view.status==='pending_acknowledgement'&&<button onClick={()=>setAckTarget(view)} className="rounded-xl bg-orange-600 px-4 py-2 text-white">บันทึกการรับทราบแทนพนักงาน</button>}{view.status==='termination_review'&&<button onClick={()=>setDecisionTarget(view)} className="rounded-xl bg-slate-900 px-4 py-2 text-white">บันทึกผลพิจารณา</button>}{['acknowledged','acknowledgement_refused'].includes(view.status)&&<button onClick={()=>act(view,'close')} className="rounded-xl bg-gray-700 px-4 py-2 text-white">ปิดเคส</button>}{!['closed','cancelled'].includes(view.status)&&<button onClick={()=>act(view,'cancel')} className="rounded-xl border border-red-300 px-4 py-2 text-red-600">ยกเลิกเคส</button>}</div>}</div>}</Modal>
    <Modal open={!!ackTarget} onClose={()=>setAckTarget(null)} contentClassName="max-w-xl"><div className="space-y-4 p-6"><h2 className="text-xl font-bold">บันทึกการรับทราบ</h2><Field label="ผล"><select className="input" value={ackForm.outcome} onChange={e=>setAckForm(f=>({...f,outcome:e.target.value as typeof f.outcome}))}><option value="acknowledged">พนักงานรับทราบ</option><option value="refused">พนักงานปฏิเสธการลงนามรับทราบ</option></select></Field><Field label="วิธีรับทราบ"><select className="input" value={ackForm.method} onChange={e=>setAckForm(f=>({...f,method:e.target.value}))}><option value="in_person">ต่อหน้า</option><option value="video_call">วิดีโอคอล</option><option value="registered_mail">ไปรษณีย์ลงทะเบียน</option><option value="other">อื่น ๆ</option></select></Field>{ackForm.outcome==='refused'&&<Field label="พยาน *"><select className="input" value={ackForm.witness_id} onChange={e=>setAckForm(f=>({...f,witness_id:e.target.value}))}><option value="">เลือกพยาน</option>{employees.map(e=><option key={e.id} value={e.id}>{empName(e)}</option>)}</select></Field>}<Field label="คำชี้แจง / บันทึกเหตุการณ์"><textarea className="input" rows={3} value={ackForm.note} onChange={e=>setAckForm(f=>({...f,note:e.target.value}))}/></Field><button onClick={saveAcknowledgement} className="w-full rounded-xl bg-orange-600 py-3 text-white">บันทึก</button></div></Modal>
    <Modal open={!!actionTarget} onClose={()=>setActionTarget(null)} contentClassName="max-w-lg"><div className="space-y-5 p-6"><div className="pr-12"><h2 className="text-xl font-bold">{actionTarget?.action==='return'?'ส่งกลับแก้ไข':actionTarget?.action==='close'?'ยืนยันปิดเคส':'ยกเลิกเคส'}</h2><p className="mt-1 text-sm text-gray-500">{actionTarget?.warning.case_number} · {actionTarget?.warning.subject}</p></div>{actionTarget?.action==='close'?<p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">เมื่อปิดเคสแล้ว รายการจะถูกบันทึกเป็นประวัติที่เสร็จสิ้น ต้องการปิดเคสนี้หรือไม่?</p>:<Field label={actionTarget?.action==='return'?'เหตุผลที่ส่งกลับแก้ไข *':'เหตุผลที่ยกเลิกเคส *'}><textarea autoFocus className="input" rows={4} value={actionNote} onChange={e=>setActionNote(e.target.value)} placeholder="กรุณาระบุเหตุผล..."/></Field>}<div className="flex justify-end"><button type="button" onClick={confirmAction} disabled={actionTarget?.action!=='close'&&!actionNote.trim()} className={`rounded-xl px-6 py-3 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50 ${actionTarget?.action==='return'?'bg-blue-600':actionTarget?.action==='close'?'bg-gray-700':'bg-red-600'}`}>{actionTarget?.action==='close'?'ยืนยันปิดเคส':'ยืนยัน'}</button></div></div></Modal>
    <Modal open={!!decisionTarget} onClose={()=>setDecisionTarget(null)} contentClassName="max-w-xl"><div className="space-y-4 p-6"><h2 className="text-xl font-bold">ผลพิจารณาเลิกจ้าง</h2><Field label="ผลการพิจารณา"><select className="input" value={decision.outcome} onChange={e=>setDecision(d=>({...d,outcome:e.target.value as HRWarningDecision['outcome']}))}><option value="terminated">เลิกจ้าง</option><option value="continued_employment">ให้โอกาสปฏิบัติงานต่อ</option><option value="other_discipline">ลงโทษทางวินัยอื่น</option><option value="cancelled">ยกเลิกการดำเนินการ</option><option value="other">อื่น ๆ</option></select></Field><Field label="เหตุผล *"><textarea className="input" rows={3} value={decision.reason} onChange={e=>setDecision(d=>({...d,reason:e.target.value}))}/></Field>{decision.outcome==='continued_employment'&&<Field label="เงื่อนไขที่ต้องปฏิบัติ"><textarea className="input" rows={3} value={decision.conditions} onChange={e=>setDecision(d=>({...d,conditions:e.target.value}))}/></Field>}<Field label="วันที่มีผล"><input type="date" className="input" value={decision.effective_date} onChange={e=>setDecision(d=>({...d,effective_date:e.target.value}))}/></Field><button onClick={saveDecision} className="w-full rounded-xl bg-slate-900 py-3 text-white">บันทึกผลและปิดเคส</button></div></Modal>
    <style>{`.input{width:100%;border:1px solid #d1d5db;border-radius:.75rem;padding:.625rem .75rem;background:white}.input:focus{outline:none;border-color:#059669;box-shadow:0 0 0 3px #d1fae5}`}</style>{ConfirmModal}{MessageModal}
  </div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1 block text-sm font-medium">{label}</span>{children}</label>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl border p-3"><div className="text-xs text-gray-500">{label}</div><div className="mt-1 font-medium">{value}</div></div>}
function Section({title,text}:{title:string;text?:string|null}){return <div><h3 className="font-semibold">{title}</h3><div className="mt-2 whitespace-pre-wrap rounded-xl bg-gray-50 p-3 text-sm">{text||'-'}</div></div>}
function Timeline({title,rows}:{title:string;rows:string[]}){return <div><h3 className="font-semibold">{title}</h3><div className="mt-2 space-y-2 border-l-2 border-slate-200 pl-4">{rows.map((x,i)=><div key={i} className="text-sm text-gray-700">{x}</div>)}</div></div>}
