-- Historical inventory balances for Warehouse > Inventory Balance List.
BEGIN;

CREATE TABLE IF NOT EXISTS public.inv_stock_balance_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id UUID NOT NULL REFERENCES public.pr_products(id) ON DELETE CASCADE,
  on_hand NUMERIC(12,2) NOT NULL DEFAULT 0,
  reserved NUMERIC(12,2) NOT NULL DEFAULT 0,
  safety_stock NUMERIC(12,2) NOT NULL DEFAULT 0,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_inv_stock_balance_history_product_time
  ON public.inv_stock_balance_history (product_id, recorded_at DESC, id DESC);

ALTER TABLE public.inv_stock_balance_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS inv_stock_balance_history_select ON public.inv_stock_balance_history;
CREATE POLICY inv_stock_balance_history_select ON public.inv_stock_balance_history
  FOR SELECT TO authenticated USING (TRUE);

CREATE OR REPLACE FUNCTION public.capture_inv_stock_balance_history()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'INSERT'
     OR OLD.on_hand IS DISTINCT FROM NEW.on_hand
     OR OLD.reserved IS DISTINCT FROM NEW.reserved
     OR OLD.safety_stock IS DISTINCT FROM NEW.safety_stock THEN
    INSERT INTO public.inv_stock_balance_history (product_id, on_hand, reserved, safety_stock, recorded_at)
    VALUES (NEW.product_id, COALESCE(NEW.on_hand, 0), COALESCE(NEW.reserved, 0), COALESCE(NEW.safety_stock, 0), NOW());
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_capture_inv_stock_balance_history ON public.inv_stock_balances;
CREATE TRIGGER trg_capture_inv_stock_balance_history
  AFTER INSERT OR UPDATE OF on_hand, reserved, safety_stock ON public.inv_stock_balances
  FOR EACH ROW EXECUTE FUNCTION public.capture_inv_stock_balance_history();

INSERT INTO public.inv_stock_balance_history (product_id, on_hand, reserved, safety_stock, recorded_at)
SELECT b.product_id, COALESCE(b.on_hand, 0), COALESCE(b.reserved, 0), COALESCE(b.safety_stock, 0), NOW()
FROM public.inv_stock_balances b
WHERE NOT EXISTS (
  SELECT 1 FROM public.inv_stock_balance_history h WHERE h.product_id = b.product_id
);

CREATE OR REPLACE FUNCTION public.rpc_inventory_balances_as_of(p_as_of_date DATE)
RETURNS TABLE (
  product_id UUID,
  product_code TEXT,
  product_name TEXT,
  product_type TEXT,
  product_category TEXT,
  is_active BOOLEAN,
  on_hand NUMERIC,
  safety_stock NUMERIC,
  total_in_stock NUMERIC
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  WITH params AS (
    SELECT ((p_as_of_date + 1)::timestamp AT TIME ZONE 'Asia/Bangkok') AS cutoff
  ),
  future_movements AS (
    SELECT m.product_id, COALESCE(SUM(m.qty), 0) AS qty
    FROM public.inv_stock_movements m, params x
    WHERE m.created_at >= x.cutoff
    GROUP BY m.product_id
  ),
  future_safety_changes AS (
    SELECT i.product_id,
      COALESCE(SUM(COALESCE(i.after_safety_stock, i.new_safety_stock, 0) - COALESCE(i.before_safety_stock, 0)), 0) AS qty
    FROM public.inv_adjustment_items i
    JOIN public.inv_adjustments a ON a.id = i.adjustment_id
    CROSS JOIN params x
    WHERE a.status = 'approved'
      AND COALESCE(a.approved_at, a.created_at) >= x.cutoff
      AND (i.after_safety_stock IS NOT NULL OR i.new_safety_stock IS NOT NULL)
    GROUP BY i.product_id
  )
  SELECT
    p.id,
    p.product_code,
    p.product_name,
    p.product_type,
    p.product_category,
    COALESCE(p.is_active, TRUE),
    ROUND(CASE
      WHEN snap.id IS NOT NULL THEN snap.on_hand
      WHEN p.created_at >= x.cutoff THEN 0
      ELSE (COALESCE(b.on_hand, 0) + COALESCE(b.safety_stock, 0) - COALESCE(fm.qty, 0))
           - (COALESCE(b.safety_stock, 0) - COALESCE(fs.qty, 0))
    END, 2) AS on_hand,
    ROUND(CASE
      WHEN snap.id IS NOT NULL THEN snap.safety_stock
      WHEN p.created_at >= x.cutoff THEN 0
      ELSE COALESCE(b.safety_stock, 0) - COALESCE(fs.qty, 0)
    END, 2) AS safety_stock,
    ROUND(CASE
      WHEN snap.id IS NOT NULL THEN snap.on_hand + snap.safety_stock
      WHEN p.created_at >= x.cutoff THEN 0
      ELSE COALESCE(b.on_hand, 0) + COALESCE(b.safety_stock, 0) - COALESCE(fm.qty, 0)
    END, 2) AS total_in_stock
  FROM public.pr_products p
  CROSS JOIN params x
  LEFT JOIN public.inv_stock_balances b ON b.product_id = p.id
  LEFT JOIN future_movements fm ON fm.product_id = p.id
  LEFT JOIN future_safety_changes fs ON fs.product_id = p.id
  LEFT JOIN LATERAL (
    SELECT h.id, h.on_hand, h.safety_stock
    FROM public.inv_stock_balance_history h
    WHERE h.product_id = p.id AND h.recorded_at < x.cutoff
    ORDER BY h.recorded_at DESC, h.id DESC
    LIMIT 1
  ) snap ON TRUE
  ORDER BY p.product_code;
$$;

REVOKE ALL ON FUNCTION public.rpc_inventory_balances_as_of(DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_inventory_balances_as_of(DATE) TO authenticated;
GRANT SELECT ON public.inv_stock_balance_history TO authenticated;

INSERT INTO public.st_user_menus (role, menu_key, menu_name, has_access)
VALUES
  ('superadmin', 'warehouse-inventory-history', 'รายการสินค้าคงเหลือ', TRUE),
  ('admin', 'warehouse-inventory-history', 'รายการสินค้าคงเหลือ', TRUE),
  ('store', 'warehouse-inventory-history', 'รายการสินค้าคงเหลือ', TRUE)
ON CONFLICT (role, menu_key) DO UPDATE SET
  menu_name = EXCLUDED.menu_name,
  has_access = EXCLUDED.has_access,
  updated_at = NOW();

COMMIT;

NOTIFY pgrst, 'reload schema';
