-- Alternate/special-delivery postal codes used by carriers.
-- A sub-district can have more than one deliverable postal code, while
-- thai_sub_districts keeps the canonical administrative postal code.

CREATE TABLE IF NOT EXISTS thai_sub_district_postal_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sub_district_id BIGINT NOT NULL REFERENCES thai_sub_districts(id) ON DELETE CASCADE,
  zip_code TEXT NOT NULL CHECK (zip_code ~ '^[0-9]{5}$'),
  source TEXT NOT NULL DEFAULT 'carrier',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT thai_sub_district_postal_aliases_unique UNIQUE (sub_district_id, zip_code)
);

CREATE INDEX IF NOT EXISTS idx_thai_sub_district_postal_aliases_zip
  ON thai_sub_district_postal_aliases(zip_code);

ALTER TABLE thai_sub_district_postal_aliases ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON thai_sub_district_postal_aliases TO anon, authenticated;

DROP POLICY IF EXISTS "Allow read thai sub-district postal aliases" ON thai_sub_district_postal_aliases;
CREATE POLICY "Allow read thai sub-district postal aliases"
  ON thai_sub_district_postal_aliases FOR SELECT
  TO anon, authenticated
  USING (TRUE);

-- Audited against Template_ค่าขนส่งพื้นที่พิเศษ_กรอกแล้ว.xlsx.
-- Every referenced sub-district already exists; only the carrier postal-code
-- mapping was absent. ON CONFLICT makes the migration safe to run repeatedly.
INSERT INTO thai_sub_district_postal_aliases (sub_district_id, zip_code, source)
VALUES
  (502502, '58130', 'Flash Express'), -- แม่แดด / กัลยาณิวัฒนา / เชียงใหม่
  (940904, '94150', 'Flash Express'), -- ตันหยงจึงงา / ยะหริ่ง / ปัตตานี
  (960506, '96130', 'Flash Express'), -- บองอ / ระแงะ / นราธิวาส
  (940504, '94190', 'Flash Express'), -- กระหวะ / มายอ / ปัตตานี
  (940404, '94190', 'Flash Express'), -- ดอน / ปะนาเระ / ปัตตานี
  (200402, '20260', 'Flash Express'), -- หนองปรือ / บางละมุง / ชลบุรี
  (810117, '81180', 'Flash Express'), -- หนองทะเล / เมืองกระบี่ / กระบี่
  (810116, '81180', 'Flash Express'), -- อ่าวนาง / เมืองกระบี่ / กระบี่
  (810116, '81210', 'Flash Express'), -- อ่าวนาง / เมืองกระบี่ / กระบี่
  (820404, '82140', 'Flash Express'), -- ท่าอยู่ / ตะกั่วทุ่ง / พังงา
  (820407, '82140', 'Flash Express'), -- คลองเคียน / ตะกั่วทุ่ง / พังงา
  (820504, '82190', 'Flash Express'), -- บางม่วง / ตะกั่วป่า / พังงา
  (820507, '82220', 'Flash Express'), -- คึกคัก / ตะกั่วป่า / พังงา
  (830106, '83000', 'Flash Express'), -- ฉลอง / เมืองภูเก็ต / ภูเก็ต
  (830107, '83100', 'Flash Express'), -- ราไวย์ / เมืองภูเก็ต / ภูเก็ต
  (830203, '83120', 'Flash Express'), -- กมลา / กะทู้ / ภูเก็ต
  (830201, '83150', 'Flash Express'), -- กะทู้ / กะทู้ / ภูเก็ต
  (840401, '84220', 'Flash Express'), -- อ่างทอง / เกาะสมุย / สุราษฎร์ธานี
  (840503, '84360', 'Flash Express')  -- เกาะเต่า / เกาะพะงัน / สุราษฎร์ธานี
ON CONFLICT (sub_district_id, zip_code) DO UPDATE
SET source = EXCLUDED.source;

NOTIFY pgrst, 'reload schema';
