-- QT/PC: sales documents that exist before a real order is created.
-- They intentionally live outside or_orders so they cannot enter WMS/QC/accounting flows.

CREATE TABLE IF NOT EXISTS public.or_prebill_channel_settings (
  channel_code TEXT NOT NULL REFERENCES public.channels(channel_code) ON UPDATE CASCADE ON DELETE CASCADE,
  document_type TEXT NOT NULL CHECK (document_type IN ('quotation', 'production_confirmation')),
  document_prefix TEXT NOT NULL,
  header_name TEXT NOT NULL,
  default_valid_days INTEGER NOT NULL DEFAULT 7 CHECK (default_valid_days BETWEEN 1 AND 365),
  updated_by UUID REFERENCES public.us_users(id) ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (channel_code, document_type)
);

CREATE TABLE IF NOT EXISTS public.or_prebill_number_sequences (
  channel_code TEXT NOT NULL,
  document_type TEXT NOT NULL CHECK (document_type IN ('quotation', 'production_confirmation')),
  period CHAR(4) NOT NULL,
  last_number INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (channel_code, document_type, period)
);

CREATE TABLE IF NOT EXISTS public.or_prebill_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_type TEXT NOT NULL CHECK (document_type IN ('quotation', 'production_confirmation')),
  document_no TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN (
    'draft', 'active', 'pending_discount', 'approved', 'rejected',
    'expired', 'converted', 'cancelled'
  )),
  channel_code TEXT NOT NULL REFERENCES public.channels(channel_code) ON UPDATE CASCADE,
  header_name TEXT NOT NULL,
  customer_name TEXT NOT NULL DEFAULT 'ลูกค้า',
  customer_address TEXT,
  recipient_name TEXT,
  customer_phone TEXT,
  billing_details JSONB NOT NULL DEFAULT '{}'::jsonb,
  delivery_term TEXT NOT NULL DEFAULT '1-3 วัน',
  valid_until DATE NOT NULL,
  payment_method TEXT,
  subtotal NUMERIC(14,2) NOT NULL DEFAULT 0,
  shipping_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
  promotion_discount NUMERIC(14,2) NOT NULL DEFAULT 0,
  special_discount NUMERIC(14,2) NOT NULL DEFAULT 0,
  special_discount_type TEXT CHECK (special_discount_type IS NULL OR special_discount_type IN ('amount', 'percent')),
  special_discount_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  promotion_ids UUID[] NOT NULL DEFAULT '{}'::uuid[],
  promotion_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
  shipping_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  internal_note TEXT,
  discount_request_note TEXT,
  discount_requested_at TIMESTAMPTZ,
  discount_requested_by UUID REFERENCES public.us_users(id) ON DELETE SET NULL,
  approved_special_discount NUMERIC(14,2),
  approval_note TEXT,
  approved_at TIMESTAMPTZ,
  approved_by UUID REFERENCES public.us_users(id) ON DELETE SET NULL,
  rejection_note TEXT,
  converted_order_id UUID UNIQUE REFERENCES public.or_orders(id) ON DELETE SET NULL,
  converted_at TIMESTAMPTZ,
  source_document_id UUID REFERENCES public.or_prebill_documents(id) ON DELETE SET NULL,
  owner_id UUID NOT NULL REFERENCES public.us_users(id) ON DELETE RESTRICT DEFAULT auth.uid(),
  owner_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT or_prebill_non_negative CHECK (
    subtotal >= 0 AND shipping_cost >= 0 AND promotion_discount >= 0
    AND special_discount >= 0 AND special_discount_value >= 0 AND total_amount >= 0
  )
);

CREATE TABLE IF NOT EXISTS public.or_prebill_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id UUID NOT NULL REFERENCES public.or_prebill_documents(id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  product_id UUID REFERENCES public.pr_products(id) ON DELETE SET NULL,
  product_code TEXT,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
  is_free BOOLEAN NOT NULL DEFAULT false,
  is_detail_row BOOLEAN NOT NULL DEFAULT false,
  parent_item_id UUID,
  oh_snapshot NUMERIC NOT NULL DEFAULT 0,
  ink_color TEXT,
  product_type TEXT,
  cartoon_pattern TEXT,
  line_pattern TEXT,
  font TEXT,
  line_1 TEXT,
  line_2 TEXT,
  line_3 TEXT,
  no_name_line BOOLEAN NOT NULL DEFAULT false,
  notes TEXT,
  file_attachment TEXT,
  attachment_name TEXT,
  field_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.or_prebill_items
  ADD CONSTRAINT or_prebill_items_parent_item_fk
  FOREIGN KEY (parent_item_id) REFERENCES public.or_prebill_items(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS public.or_prebill_approval_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id UUID NOT NULL REFERENCES public.or_prebill_documents(id) ON DELETE CASCADE,
  action TEXT NOT NULL CHECK (action IN ('requested', 'approved', 'rejected', 'edited_by_superadmin')),
  requested_discount NUMERIC(14,2),
  approved_discount NUMERIC(14,2),
  note TEXT,
  actor_id UUID REFERENCES public.us_users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  actor_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_prebill_owner_created ON public.or_prebill_documents(owner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_prebill_type_status ON public.or_prebill_documents(document_type, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_prebill_valid_until ON public.or_prebill_documents(valid_until);
CREATE INDEX IF NOT EXISTS idx_prebill_items_document ON public.or_prebill_items(document_id, sort_order);

ALTER TABLE public.or_orders
  ADD COLUMN IF NOT EXISTS source_prebill_document_id UUID UNIQUE
  REFERENCES public.or_prebill_documents(id) ON DELETE SET NULL;

ALTER TABLE public.or_orders
  ADD COLUMN IF NOT EXISTS prebill_price_locked BOOLEAN NOT NULL DEFAULT false;

CREATE OR REPLACE FUNCTION public.rpc_next_prebill_document_no(p_channel_code TEXT, p_document_type TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role TEXT;
  v_period TEXT := to_char(timezone('Asia/Bangkok', now()), 'YYMM');
  v_number INTEGER;
  v_prefix TEXT;
BEGIN
  SELECT role INTO v_role FROM public.us_users WHERE id = auth.uid();
  IF v_role NOT IN ('superadmin', 'sales-tr', 'sales-pump') THEN
    RAISE EXCEPTION 'ไม่มีสิทธิ์สร้างเอกสาร QT/PC';
  END IF;
  IF p_document_type NOT IN ('quotation', 'production_confirmation') THEN
    RAISE EXCEPTION 'ประเภทเอกสารไม่ถูกต้อง';
  END IF;

  SELECT document_prefix INTO v_prefix
  FROM public.or_prebill_channel_settings
  WHERE channel_code = btrim(p_channel_code) AND document_type = p_document_type;

  v_prefix := COALESCE(NULLIF(btrim(v_prefix), ''),
    CASE WHEN p_document_type = 'quotation' THEN 'QT' ELSE 'PC' END || '-' || upper(btrim(p_channel_code)));

  INSERT INTO public.or_prebill_number_sequences(channel_code, document_type, period, last_number)
  VALUES (btrim(p_channel_code), p_document_type, v_period, 1)
  ON CONFLICT (channel_code, document_type, period)
  DO UPDATE SET last_number = public.or_prebill_number_sequences.last_number + 1
  RETURNING last_number INTO v_number;

  RETURN v_prefix || '-' || v_period || '-' || lpad(v_number::TEXT, 4, '0');
END;
$$;

CREATE OR REPLACE FUNCTION public.rpc_request_prebill_discount(
  p_document_id UUID, p_discount_type TEXT, p_discount_value NUMERIC, p_note TEXT
)
RETURNS public.or_prebill_documents
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_doc public.or_prebill_documents;
  v_role TEXT;
  v_name TEXT;
  v_discount NUMERIC;
BEGIN
  SELECT role, COALESCE(username, email) INTO v_role, v_name FROM public.us_users WHERE id = auth.uid();
  SELECT * INTO v_doc FROM public.or_prebill_documents WHERE id = p_document_id FOR UPDATE;
  IF v_doc.id IS NULL OR (v_role <> 'superadmin' AND v_doc.owner_id <> auth.uid()) THEN RAISE EXCEPTION 'ไม่มีสิทธิ์'; END IF;
  IF v_doc.status NOT IN ('draft', 'active', 'rejected') THEN RAISE EXCEPTION 'สถานะเอกสารไม่อนุญาตให้ขอส่วนลด'; END IF;
  IF p_discount_type NOT IN ('amount', 'percent') OR p_discount_value <= 0 THEN RAISE EXCEPTION 'ส่วนลดไม่ถูกต้อง'; END IF;
  IF btrim(COALESCE(p_note, '')) = '' THEN RAISE EXCEPTION 'กรุณาระบุหมายเหตุคำขอ'; END IF;
  v_discount := CASE WHEN p_discount_type = 'percent'
    THEN round(v_doc.subtotal * least(p_discount_value, 100) / 100, 2)
    ELSE least(p_discount_value, v_doc.subtotal)
  END;
  UPDATE public.or_prebill_documents SET
    status = 'pending_discount', special_discount_type = p_discount_type,
    special_discount_value = p_discount_value, special_discount = v_discount,
    discount_request_note = btrim(p_note), discount_requested_at = now(),
    discount_requested_by = auth.uid(), approved_special_discount = NULL,
    approved_at = NULL, approved_by = NULL, approval_note = NULL, rejection_note = NULL,
    total_amount = greatest(0, subtotal + shipping_cost - promotion_discount - v_discount), updated_at = now()
  WHERE id = p_document_id RETURNING * INTO v_doc;
  INSERT INTO public.or_prebill_approval_logs(document_id, action, requested_discount, note, actor_id, actor_name)
  VALUES (p_document_id, 'requested', v_discount, btrim(p_note), auth.uid(), v_name);
  RETURN v_doc;
END;
$$;

CREATE OR REPLACE FUNCTION public.rpc_review_prebill_discount(
  p_document_id UUID, p_approve BOOLEAN, p_approved_discount NUMERIC, p_note TEXT
)
RETURNS public.or_prebill_documents
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_doc public.or_prebill_documents;
  v_name TEXT;
  v_requested NUMERIC;
BEGIN
  IF NOT public.check_user_role(auth.uid(), ARRAY['superadmin']) THEN RAISE EXCEPTION 'เฉพาะ superadmin เท่านั้น'; END IF;
  SELECT COALESCE(username, email) INTO v_name FROM public.us_users WHERE id = auth.uid();
  SELECT * INTO v_doc FROM public.or_prebill_documents WHERE id = p_document_id FOR UPDATE;
  IF v_doc.status <> 'pending_discount' THEN RAISE EXCEPTION 'เอกสารไม่ได้รออนุมัติ'; END IF;
  v_requested := v_doc.special_discount;
  IF p_approve THEN
    UPDATE public.or_prebill_documents SET status = 'approved',
      approved_special_discount = greatest(0, least(COALESCE(p_approved_discount, special_discount), subtotal)),
      special_discount = greatest(0, least(COALESCE(p_approved_discount, special_discount), subtotal)),
      approved_at = now(), approved_by = auth.uid(), approval_note = NULLIF(btrim(COALESCE(p_note,'')), ''),
      rejection_note = NULL,
      total_amount = greatest(0, subtotal + shipping_cost - promotion_discount - greatest(0, least(COALESCE(p_approved_discount, special_discount), subtotal))),
      updated_at = now()
    WHERE id = p_document_id RETURNING * INTO v_doc;
    INSERT INTO public.or_prebill_approval_logs(document_id, action, requested_discount, approved_discount, note, actor_id, actor_name)
    VALUES (p_document_id, 'approved', v_requested, v_doc.approved_special_discount, p_note, auth.uid(), v_name);
  ELSE
    UPDATE public.or_prebill_documents SET status = 'rejected', rejection_note = NULLIF(btrim(COALESCE(p_note,'')), ''),
      special_discount = 0, total_amount = greatest(0, subtotal + shipping_cost - promotion_discount), updated_at = now()
    WHERE id = p_document_id RETURNING * INTO v_doc;
    INSERT INTO public.or_prebill_approval_logs(document_id, action, requested_discount, note, actor_id, actor_name)
    VALUES (p_document_id, 'rejected', v_requested, p_note, auth.uid(), v_name);
  END IF;
  RETURN v_doc;
END;
$$;

CREATE OR REPLACE FUNCTION public.guard_prebill_document_update()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
DECLARE v_role TEXT;
BEGIN
  SELECT role INTO v_role FROM public.us_users WHERE id = auth.uid();
  IF TG_OP = 'INSERT' THEN
    IF v_role <> 'superadmin' AND (
      NEW.status NOT IN ('draft', 'active') OR NEW.approved_by IS NOT NULL
      OR NEW.approved_at IS NOT NULL OR NEW.approved_special_discount IS NOT NULL
    ) THEN
      RAISE EXCEPTION 'ไม่มีสิทธิ์กำหนดสถานะอนุมัติ';
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
  END IF;
  IF v_role <> 'superadmin' THEN
    IF NEW.status = 'approved'
       OR NEW.approved_by IS DISTINCT FROM OLD.approved_by
       OR NEW.approved_at IS DISTINCT FROM OLD.approved_at
       OR NEW.approved_special_discount IS DISTINCT FROM OLD.approved_special_discount THEN
      RAISE EXCEPTION 'เฉพาะ superadmin เท่านั้นที่อนุมัติส่วนลดได้';
    END IF;
    IF NEW.special_discount IS DISTINCT FROM OLD.special_discount AND NEW.status <> 'pending_discount' THEN
      RAISE EXCEPTION 'ส่วนลดพิเศษต้องส่งคำขออนุมัติ';
    END IF;
    IF NEW.status IS DISTINCT FROM OLD.status AND NOT (
      (OLD.status IN ('draft', 'active', 'rejected') AND NEW.status IN ('draft', 'active'))
      OR (OLD.status IN ('draft', 'active', 'rejected') AND NEW.status = 'pending_discount'
          AND NEW.discount_requested_by = auth.uid() AND btrim(COALESCE(NEW.discount_request_note, '')) <> '')
      OR (OLD.status IN ('active', 'approved') AND NEW.status = 'converted' AND NEW.converted_order_id IS NOT NULL)
    ) THEN
      RAISE EXCEPTION 'ไม่มีสิทธิ์เปลี่ยนสถานะเอกสาร';
    END IF;
  END IF;
  IF v_role <> 'superadmin' AND OLD.status IN ('pending_discount', 'approved', 'converted', 'cancelled')
     AND NOT (OLD.status = 'approved' AND NEW.status = 'converted' AND NEW.converted_order_id IS NOT NULL) THEN
    RAISE EXCEPTION 'เอกสารถูกล็อก แก้ไขได้โดย superadmin เท่านั้น';
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_guard_prebill_document_update ON public.or_prebill_documents;
CREATE TRIGGER trg_guard_prebill_document_update BEFORE INSERT OR UPDATE ON public.or_prebill_documents
FOR EACH ROW EXECUTE FUNCTION public.guard_prebill_document_update();

CREATE OR REPLACE FUNCTION public.rpc_convert_prebill_to_order(p_document_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_doc public.or_prebill_documents;
  v_role TEXT;
  v_bill_no TEXT;
  v_order_id UUID;
  v_period TEXT := to_char(timezone('Asia/Bangkok', now()), 'YYMM');
  v_last INTEGER;
  v_promotion_names TEXT;
BEGIN
  SELECT role INTO v_role FROM public.us_users WHERE id = auth.uid();
  SELECT * INTO v_doc FROM public.or_prebill_documents WHERE id = p_document_id FOR UPDATE;
  IF v_doc.id IS NULL OR (v_role <> 'superadmin' AND v_doc.owner_id <> auth.uid()) THEN RAISE EXCEPTION 'ไม่มีสิทธิ์'; END IF;
  IF v_doc.converted_order_id IS NOT NULL OR v_doc.status = 'converted' THEN RAISE EXCEPTION 'เอกสารนี้เปิดบิลแล้ว'; END IF;
  IF v_doc.valid_until < timezone('Asia/Bangkok', now())::DATE THEN RAISE EXCEPTION 'เอกสารหมดอายุ กรุณาสร้างเอกสารใหม่'; END IF;
  IF v_doc.status NOT IN ('active', 'approved') THEN RAISE EXCEPTION 'สถานะเอกสารยังไม่พร้อมเปิดบิล'; END IF;

  PERFORM pg_advisory_xact_lock(hashtext(v_doc.channel_code || v_period));
  SELECT COALESCE(max(CASE WHEN right(bill_no, 4) ~ '^[0-9]{4}$' THEN right(bill_no, 4)::INTEGER END), 0) INTO v_last
  FROM public.or_orders
  WHERE bill_no LIKE v_doc.channel_code || v_period || '____';
  v_bill_no := v_doc.channel_code || v_period || lpad((v_last + 1)::TEXT, 4, '0');
  SELECT string_agg(x->>'name', ', ') INTO v_promotion_names
  FROM jsonb_array_elements(v_doc.promotion_snapshot) x;

  INSERT INTO public.or_orders(
    channel_code, bill_no, status, price, shipping_cost, discount, total_amount,
    payment_method, promotion, customer_name, customer_address, admin_user,
    entry_date, billing_details, source_prebill_document_id, prebill_price_locked
  ) VALUES (
    v_doc.channel_code, v_bill_no, 'รอลงข้อมูล', v_doc.subtotal, v_doc.shipping_cost,
    v_doc.promotion_discount + v_doc.special_discount, v_doc.total_amount,
    v_doc.payment_method, v_promotion_names, v_doc.customer_name, COALESCE(v_doc.customer_address, ''),
    v_doc.owner_name, timezone('Asia/Bangkok', now())::DATE, v_doc.billing_details,
    v_doc.id, true
  ) RETURNING id INTO v_order_id;

  INSERT INTO public.or_order_items(
    id, order_id, item_uid, product_id, product_name, quantity, unit_price,
    ink_color, product_type, cartoon_pattern, line_pattern, font,
    line_1, line_2, line_3, no_name_line, is_free, notes,
    file_attachment, attachment_name, is_detail_row, parent_item_id
  )
  SELECT i.id, v_order_id, v_bill_no || '-' || row_number() OVER (ORDER BY i.sort_order, i.id),
    i.product_id, i.product_name, i.quantity, CASE WHEN i.is_free THEN 0 ELSE i.unit_price END,
    i.ink_color, i.product_type, i.cartoon_pattern, i.line_pattern, i.font,
    i.line_1, i.line_2, i.line_3, i.no_name_line, i.is_free, i.notes,
    i.file_attachment, i.attachment_name, i.is_detail_row, i.parent_item_id
  FROM public.or_prebill_items i WHERE i.document_id = v_doc.id ORDER BY i.sort_order, i.id;

  UPDATE public.or_prebill_documents
  SET status = 'converted', converted_order_id = v_order_id, converted_at = now(), updated_at = now()
  WHERE id = v_doc.id;

  RETURN jsonb_build_object('order_id', v_order_id, 'bill_no', v_bill_no);
END;
$$;

ALTER TABLE public.or_prebill_channel_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.or_prebill_number_sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.or_prebill_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.or_prebill_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.or_prebill_approval_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY prebill_settings_read ON public.or_prebill_channel_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY prebill_settings_superadmin ON public.or_prebill_channel_settings FOR ALL TO authenticated
  USING (public.check_user_role(auth.uid(), ARRAY['superadmin']))
  WITH CHECK (public.check_user_role(auth.uid(), ARRAY['superadmin']));

CREATE POLICY prebill_documents_select ON public.or_prebill_documents FOR SELECT TO authenticated
  USING (owner_id = auth.uid() OR public.check_user_role(auth.uid(), ARRAY['superadmin']));
CREATE POLICY prebill_documents_insert ON public.or_prebill_documents FOR INSERT TO authenticated
  WITH CHECK (owner_id = auth.uid() AND public.check_user_role(auth.uid(), ARRAY['superadmin','sales-tr','sales-pump']));
CREATE POLICY prebill_documents_update ON public.or_prebill_documents FOR UPDATE TO authenticated
  USING (owner_id = auth.uid() OR public.check_user_role(auth.uid(), ARRAY['superadmin']))
  WITH CHECK (owner_id = auth.uid() OR public.check_user_role(auth.uid(), ARRAY['superadmin']));

CREATE POLICY prebill_items_select ON public.or_prebill_items FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.or_prebill_documents d WHERE d.id = document_id));
CREATE POLICY prebill_items_write ON public.or_prebill_items FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.or_prebill_documents d WHERE d.id = document_id AND (d.owner_id = auth.uid() OR public.check_user_role(auth.uid(), ARRAY['superadmin']))))
  WITH CHECK (EXISTS (SELECT 1 FROM public.or_prebill_documents d WHERE d.id = document_id AND (d.owner_id = auth.uid() OR public.check_user_role(auth.uid(), ARRAY['superadmin']))));

CREATE POLICY prebill_logs_select ON public.or_prebill_approval_logs FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.or_prebill_documents d WHERE d.id = document_id));

REVOKE ALL ON FUNCTION public.rpc_next_prebill_document_no(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.rpc_request_prebill_discount(UUID, TEXT, NUMERIC, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.rpc_review_prebill_discount(UUID, BOOLEAN, NUMERIC, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.rpc_convert_prebill_to_order(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_next_prebill_document_no(TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_request_prebill_discount(UUID, TEXT, NUMERIC, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_review_prebill_discount(UUID, BOOLEAN, NUMERIC, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_convert_prebill_to_order(UUID) TO authenticated;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.or_prebill_documents;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE public.or_prebill_documents IS 'QT/PC documents before a real order; never consumed by operational order flows';

INSERT INTO public.st_user_menus(role, menu_key, menu_name, has_access, updated_at)
SELECT role, 'orders-prebill', 'QT/PC', role IN ('sales-tr', 'sales-pump'), now()
FROM (VALUES ('admin'), ('sales-tr'), ('qc_order'), ('sales-pump'), ('qc_staff'), ('packing_staff'), ('account'), ('store'), ('production'), ('hr')) AS roles(role)
ON CONFLICT (role, menu_key) DO UPDATE SET menu_name = EXCLUDED.menu_name, has_access = EXCLUDED.has_access, updated_at = now();
